### ISSUE TITLE
[BUG] <Unable to open subgrid rows using xrmApp.Entity.SubGrid.OpenSubGridRecord>

### ISSUE THREAD

**Issue by JakeObrienMercuryXrm** [Microsoft/EasyRepro#1231]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [ X ] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [ X ] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [ X ] Online
  - [ ] On Premise

**Browser**
  - [ X ] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
When using xrmApp.Entity.SubGrid.OpenSubGridRecord it always returns an error of:

 System.ArgumentException: MoveToElement cannot move to a null element with no offset.
Parameter name: toElement
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.OpenSubGridRecord(String subgridName, Int32 index)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.SubGrid.OpenSubGridRecord(String subgridName, Int32 index)

It finds the correct subgrid but since the update and the change to the grids it is unable to open the records in the grid.

**Special formatting / display**  

**Code to reproduce**  

```csharp
xrmApp.Entity.SubGrid.OpenSubGridRecord("WorkHistory", 0);
```
 -->
 
**Expected behavior**  
The row in the subgrid is opened

**Screenshots**  
![image](https://user-images.githubusercontent.com/59575810/140089126-9ed1d911-595f-46a9-8ef7-f1c6ceea59da.png)
![image](https://user-images.githubusercontent.com/59575810/140089207-552a6b0d-f807-4696-8acf-3fd1f76d5a9c.png)

**Comment by sjakobsen95** [comment]
I am facing this issue as well. Any workaround for this?

**Comment by JakeObrienMercuryXrm** [comment]
Hey @sjakobsen95 I do have a work around but it's not great and can be fragile. Will be reverting back as soon as they get it fixed. 

If there is only ever one entry in the grid, this code below will highlight all elements in the subgrid. Once highlighted I then have an edit button that can be clicked on the subgrid command bar which I use to open the row. 

`driver.FindElement(By.XPath("//i[@data-icon-name = 'StatusCircleCheckmark']")).Click()`

Alternatively, find the an element in the row on the grid, in my example the Employer Name and click on it using selenium code which then highlights it. If I need to open it I double click on the element using the Selenium Actions.

`Actions actions = new Actions(driver);
IWebElement villa = driver.FindElement(By.XPath("//label[@title = 'Aston Villa FC']"));
actions.DoubleClick(villa).Perform();`

![image](https://user-images.githubusercontent.com/59575810/145205237-06d93570-3cf2-4e8a-b586-0f88c4155000.png)

**Comment by Shakevg** [comment]
@JakeObrienMercuryXrm Did you try develop-2021ReleaseWave2 nuget of the branch?

**Comment by JakeObrienMercuryXrm** [comment]
@Shakevg Hey, I am currently using this version '9.2.21111.116-RW2-Preview'.
