### ISSUE TITLE
xrmApp.Grid.SwitchView(View Name) not working in CRM wave 2 with 9.2.21111.116-RW2-Preview version 

### ISSUE THREAD

**Issue by AddalaDeviPriya** [Microsoft/EasyRepro#1261]
Switch view is not working for Wave 2 and test script is failing with timeout

**Comment by aliyoussefi** [comment]
Hi @AddalaDeviPriya ,

Thank you for opening this bug. Please provide additional information as I am unable to recreate on build 9.2.21122.00151.
Artifacts including screenshots of the about page located in the Settings area will be helpful.

Thanks!

Ali

**Comment by tipsey** [comment]
Experiencing this problem now

**NOTE: Installed EasyRepro-alyousse-develop-2022ReleaseWave2 and this resolved issue**

**2022 release wave 2 enabled**
Server version: 9.2.22093.00184
Client version: 1.4.4799-2209.3

Code:

xrmApp.Navigation.OpenSubArea("Accounts");
xrmApp.Grid.SwitchView("Sites"); //FAILS HERE

Test method Sanity.SanityTests.MyTest threw exception:
OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":".ms-ContextualMenu-itemText"}

at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 89
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 35
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.SwitchView(String viewName, String subViewName, Int32 thinkTime) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 1470
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.Grid.SwitchView(String viewName, String subViewName) in D:\a\1\s\Microsoft.Dynamics365.UIAutomation.Api.UCI\Elements\Grid.cs:line 23
