### ISSUE TITLE
aadtile can't be found

### ISSUE THREAD

**Issue by Misjudgments** [Microsoft/EasyRepro#1372]
## Question

**What is your question?**
so, i'm not sure exectly how related my question to here, but i've bought a code from someone, and i can see i get a selenium error that aadtile is not found, has the id changed? how can i fix it?
please tell me if i need to add more information, such as chromium version or anything else.
im using python version 3.10.10 and selenium version 4.8.3

**Comment by Shakevg** [comment]
[Misjudgments](https://github.com/Misjudgments) Please provide code example and full error log

**Comment by Misjudgments** [comment]
@Shakevg 
`driver.get('https://account.live.com/resetpassword.aspx')
    wait.until(EC.presence_of_element_located((By.ID, 'aadTile')))
    driver.find_element_by_id('aadTile').click()`
    
 `Traceback (most recent call last):
  File "C:\Users\alon\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\alon\Downloads\pain (1).py", line 110
    login(email_from_embed, otp)
  File "C:\Users\alon\Downloads\pain (1).py", line 29, in login
    wait.until(EC.presence_of_element_located((By.ID, 'aadTile')))
  File "C:\Users\alon\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        (No symbol) [0x004BDCE3]
        (No symbol) [0x004539D1]
        (No symbol) [0x00364DA8]
        (No symbol) [0x0039019F]
        (No symbol) [0x003903AB]
        (No symbol) [0x003BEE62]
        (No symbol) [0x003AAF14]
        (No symbol) [0x003BD57C]
        (No symbol) [0x003AACC6]
        (No symbol) [0x00386F68]
        (No symbol) [0x003880CD]
        GetHandleVerifier [0x00733832+2506274]
        GetHandleVerifier [0x00769794+2727300]
        GetHandleVerifier [0x0076E36C+2746716]
        GetHandleVerifier [0x00566690+617600]
        (No symbol) [0x0045C712]
        (No symbol) [0x00461FF8]
        (No symbol) [0x004620DB]
        (No symbol) [0x0046C63B]
        BaseThreadInitThunk [0x75650099+25]
        RtlGetAppContainerNamedObjectPath [0x770A7B6E+286]
        RtlGetAppContainerNamedObjectPath [0x770A7B3E+238]`
`
its a code to log into a microsoft account, but this is the part that is getting the error.
would appreciate any help, also in the error logs it says discord a few times, its because that i'm running a bot on discord.py, so ignore that.

**Comment by Shakevg** [comment]
Unfortunately, I cannot help here, because it is not related with EastRepro framework and I don't know what control are you trying to find on the page
