### ISSUE TITLE
[BUG] <Unable scroll right when column is not visible it's throwing exception>

### ISSUE THREAD

**Issue by priyaharitest** [Microsoft/EasyRepro#1391]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 9.1.0.27021
  
**UCI or Classic Web**
  -
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [x] Online
  - [ ] On Premise

**Browser**
  - [ ] Chrome

**Describe the bug**  
I need to sort records by some column. If the column is not visible in current web page , I need to scroll right then sort. But unaColumn EndDate will be displayed when scroll right.
 Column: End Date Does not exist
   at Microsoft.Dynamics365.UIAutomation.Api.Grid.<>c__DisplayClass8_0.<Sort>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)

**Special formatting / display**  

**Code to reproduce**  

 
**Expected behavior**  

**Screenshots**  

**Additional context**

**Comment by chandramohand** [comment]
Hi @priyaharitest , is this resolved?
In my case the cursor not moving to lookup field which doesn't show the field completely and throw exception, so i am trying to use the scroll down but not working.
Thanks,
Chandra.
