### ISSUE TITLE
xrmBrowser.Navigation.OpenSubArea("Sales", "Dashboards") does not work for Version 1612 (8.2.1.344) (DB 8.2.1.344) online

### ISSUE THREAD

**Issue by serjgorkun** [Microsoft/EasyRepro#15]
While working even with samples I faced an issue for all calls
`xrmBrowser.Navigation.OpenSubArea("Sales", "Leads");`
This line fails with 
`no such element: Unable to locate element: {"method":"xpath","selector":"id("TabSFA")"}
  (Session info: chrome=60.0.3112.113)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 10.0.10586 x86_64)`

   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClasse.<XPath>b__c(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.FindElement(By by)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.ClickWhenAvailable(IWebDriver driver, By by, TimeSpan timeout) in C:\Users\serhii.horkun\Downloads\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 42
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.ClickWhenAvailable(IWebDriver driver, By by) in C:\Users\serhii.horkun\Downloads\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 37
   at Microsoft.Dynamics365.UIAutomation.Api.XrmNavigationPage.<>c.<OpenMenu>b__2_0(IWebDriver driver) in C:\Users\serhii.horkun\Downloads\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Api\Pages\XrmNavigationPage.cs:line 51
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in C:\Users\serhii.horkun\Downloads\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in C:\Users\serhii.horkun\Downloads\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 111

**Comment by dtu11** [comment]
Thanks for the feedback. We're testing this now and will update this issue with what we find.

**Comment by dtu11** [comment]
We've tested this in an 8.2.1.344 org and aren't able to repro the issue.  Are you running a sample test or a custom test that you've created?  If it's custom can you include the code and we'll try that. 

Thanks

**Comment by serjgorkun** [comment]
Even samples fail for our environment. I've checked whether the names are correct. They have been in fact. 
Unfortunately for the moment I haven't got a vanilla environment. l'll try to provide more details.

**Comment by serjgorkun** [comment]
I managed to find the way to fix this problem. But another question is opened. 
For some of our environments DOM differs (for instance)
![image](https://user-images.githubusercontent.com/31663759/30271850-86953cbe-96fa-11e7-8e6b-b46d9a32ea28.png)

Do you know the reason? Or is it a normal transition to a new DOM structure?

**Comment by dtu11** [comment]
I think this may have to do with what you have as a start page.  We will adjust this to look for a DOM item above that.

**Comment by dtu11** [comment]
This issue should be resolved with the latest update.   Please test and let me know if there are any other issues.
