### ISSUE TITLE
xrmBrowser.ActivityFeed.AddTask() throws InvalidElementStateException

### ISSUE THREAD

**Issue by tomapirin** [Microsoft/EasyRepro#161]
Hello,

we are using release v9.0 on CRM v9 instance.

I am trying to **create a Task** and Call activity on Lead entity. The test method calls the xrmBrowser.ActivityFeed.AddTask("lead test", "test", new DateTime(2018, 6, 6), new OptionSet() { Name = "quickCreateActivity4212controlId_scheduledend", Value = "Normal" }); 

The Add Task button is clicked, **Subject and Description fields are filled in**, and then the executions throws an exception. We have tried the same test on relese v8.2 and CRM v8.2 instance and creates Task and Call successfully.

Exception for v9 release and CRM version:
**OpenQA.Selenium.InvalidElementStateException
  HResult=0x80131500
  Message=invalid element state: Element is not currently interactable and may not be manipulated
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.15063 x86_64)**
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Clear()
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.EventFiringWebElement.Clear()
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.SendKeys(IWebElement element, String value, Boolean clear) in C:\DEV-git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 281
   at Microsoft.Dynamics365.UIAutomation.Api.Pages.ActivityFeed.<>c__DisplayClass11_0.<SetCalenderValue>b__0(IWebDriver driver) in C:\DEV-git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api\Pages\ActivityFeed.cs:line 253
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in C:\DEV-git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in C:\DEV-git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 192
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in C:\DEV-git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](String commandName, Func`2 delegate) in C:\DEV-git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 51
   at Microsoft.Dynamics365.UIAutomation.Api.Pages.ActivityFeed.SetCalenderValue(String field, String value) in C:\DEV-git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api\Pages\ActivityFeed.cs:line 245
   at Microsoft.Dynamics365.UIAutomation.Api.Pages.ActivityFeed.<>c__DisplayClass10_0.<AddTask>b__0(IWebDriver driver) in C:\DEV-git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api\Pages\ActivityFeed.cs:line 233
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in C:\DEV-git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in C:\DEV-git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 192
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in C:\DEV-git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in C:\DEV-git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.Pages.ActivityFeed.AddTask(String subject, String description, DateTime dueDate, OptionSet priority, Int32 thinkTime) in C:\DEV-git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api\Pages\ActivityFeed.cs:line 224
   at Microsoft.Dynamics365.UIAutomation.Sample.SalesProcess.LeadConversion.PartnerLeadConversion() in C:\DEV-git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Sample\SalesProcess\LeadConversion.cs:line 92

**Comment by TYLEROL** [comment]
Thanks @tomapirin for raising this issue to us. I've added an investigation item to our backlog to take a look at why this is not working for you in the v9.0 branch with a v9.0 org.

We'll update again once we've identified the source of the issue, or if we have any follow-up questions.

Best Regards,
Tyler
