### ISSUE TITLE
EasyRepro and trial version Dynamics CRM

### ISSUE THREAD

**Issue by rijat** [Microsoft/EasyRepro#175]
Hi, 

I used EasyRepro recently, and all the tests I did do not work. 
Is that because of the trial version of my Dynamics CRM?

thanks guys

**Comment by TYLEROL** [comment]
Hello @rijat - EasyRepro will work with Trial Instances of Dynamics 365. Do you know which Version/Branch you are using?

If you recently created your trial, then it is likely on the latest version using the Unified Interface and you'll want to use the _beta/v9.0.2_ branch.

If you're still facing issues, please share more details about:

- Test/Example Code being used
- Screenshot examples of the system you're interacting with
- Browser / Browser Version being used
- Any error messages, if applicable

Best Regards,
Tyler

**Comment by rijat** [comment]
Thanks for your answer 

This is the result of test :


Name test :	WEBTestCreateNewAccount
FullName test :	Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount
Source de test :	C:\Users\...\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateAccount.cs : ligne 21
Sortie du test :	Échec
Durée du test :	0:01:03.3758665

StackTrace de résultat  :	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Click()
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.EventFiringWebElement.Click()
   at Microsoft.Dynamics365.UIAutomation.Api.Navigation.<>c.<OpenMenu>b__2_0(IWebDriver driver) in C:\Users\...\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api\Pages\Navigation.cs:line 51
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in C:\Users\....\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in C:\Users\...\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 136
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in C:\Users\...\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in C:\Users\...\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.Navigation.OpenMenu(Int32 thinkTime) in C:\Users\...\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api\Pages\Navigation.cs:line 46
   at Microsoft.Dynamics365.UIAutomation.Api.Navigation.<>c__DisplayClass3_0.<OpenSubArea>b__0(IWebDriver driver) in C:\Users\...\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api\Pages\Navigation.cs:line 85
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in C:\Users\...\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in C:\Users\....\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 136
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in C:\Users\....\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in C:\Users\....\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.Navigation.OpenSubArea(String area, String subArea, Int32 thinkTime) in C:\Users\....\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api\Pages\Navigation.cs:line 80
   at Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount() in C:\Users\....\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateAccount.cs:line 29
Message de résultat  :	
Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount threw exception: 
System.InvalidOperationException: unknown error: Element <span id="TabSFA" name="TabHome" class="navTabButton navTabButtonRight SubAreaNodePadding">...</span> is not clickable at point (319, 25). Other element would receive the click: <div id="lpathRuntimeOverlay" tabindex="-1" class="lpath-overlay-initial lpath-runtime-overlay lpath-overlay-show" style="z-index: 100001;" aria-hidden="false">...</div>
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.17134 x86_64)

**Comment by rijat** [comment]
And the code : 
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Dynamics365.UIAutomation.Api;
using Microsoft.Dynamics365.UIAutomation.Browser;
using System;
using System.Security;

namespace Microsoft.Dynamics365.UIAutomation.Sample.Web
{
    [TestClass]
    public class CreateAccount
    {

        private readonly SecureString _username = System.Configuration.ConfigurationManager.AppSettings["OnlineUsername"].ToSecureString();
        private readonly SecureString _password = System.Configuration.ConfigurationManager.AppSettings["OnlinePassword"].ToSecureString();
        private readonly Uri _xrmUri = new Uri(System.Configuration.ConfigurationManager.AppSettings["OnlineCrmUrl"].ToString());

        [TestMethod]
        public void WEBTestCreateNewAccount()
        {
            using (var xrmBrowser = new Api.Browser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
                xrmBrowser.GuidedHelp.CloseGuidedHelp();

                xrmBrowser.ThinkTime(500);
                xrmBrowser.Navigation.OpenSubArea("Sales", "Accounts");

                xrmBrowser.ThinkTime(2000);
                xrmBrowser.Grid.SwitchView("Active Accounts");

                xrmBrowser.ThinkTime(1000);
                xrmBrowser.CommandBar.ClickCommand("New");

                xrmBrowser.ThinkTime(5000);
                xrmBrowser.Entity.SetValue("name", "Test API Account");
                xrmBrowser.Entity.SetValue("telephone1", "555-555-5555");
                xrmBrowser.Entity.SetValue("websiteurl", "https://easyrepro.crm.dynamics.com");

                xrmBrowser.CommandBar.ClickCommand("Save & Close");
                xrmBrowser.ThinkTime(2000);
            }
        }
    }
}

**Comment by TYLEROL** [comment]
Sorry for the delay @rijat - I'll take a look at this scenario tomorrow and provide an update on why this test may not be working for you.

Thanks,
Tyler

**Comment by rijat** [comment]
Thanks TYROL

**Comment by TYLEROL** [comment]
Hi @rijat - Sorry for the delay on this. I have not been able to reproduce any issues with a trial environment.

From your stack trace, it looks like this is when we're trying to open the sub area path to navigate to accounts:

`xrmBrowser.Navigation.OpenSubArea("Sales", "Accounts");`

Can you confirm that you see Sales, and then Accounts in your trial environment? The current APIs only support English, so please make sure you're testing the trial organization with the English language.

Please let me know if you're still facing this issue.

Best Regards,
Tyler
