### ISSUE TITLE
UCI XrmApp test fails, but corresponding Browser test works

### ISSUE THREAD

**Issue by lucasalexander** [Microsoft/EasyRepro#185]
I have a new online trial (v9.0.2.2081), and I have built the Easy Repro libraries from the v9.0.2 beta branch. I have a test to create a new account and verify the phone number is set by a workflow using the Browser object that works fine. When I try to execute the same test using the UCI XrmApp object, I get an error. 

Here is my Browser-based test (works fine):
```
        [TestMethod]
        public void WebTestCreateAccount()
        {
            using (var xrmBrowser = new Browser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
                xrmBrowser.ThinkTime(500);

                xrmBrowser.Navigation.OpenSubArea("Sales", "Accounts");

                xrmBrowser.ThinkTime(2000);
                xrmBrowser.CommandBar.ClickCommand("New");

                xrmBrowser.ThinkTime(5000);
                xrmBrowser.Entity.SetValue("name", "Test API Account");
                xrmBrowser.Entity.SetValue("telephone1", "555-9345");
                xrmBrowser.CommandBar.ClickCommand("Save");
                xrmBrowser.ThinkTime(2000);
                Assert.AreEqual<string>("8675309", xrmBrowser.Entity.GetValue("telephone1"));
            }
        }
```
Here is my UCI test (fails):
```
        [TestMethod]
        public void UCITestCreateAccount()
        {
            var client = new WebClient(TestSettings.Options);
            using (var xrmApp = new XrmApp(client))
            {
                xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);

                xrmApp.ThinkTime(500);
                xrmApp.Navigation.OpenApp("Sales");

                xrmApp.ThinkTime(500);
                xrmApp.Navigation.OpenSubArea("Sales", "Accounts");

                xrmApp.ThinkTime(2000);
                xrmApp.CommandBar.ClickCommand("New");

                xrmApp.Entity.SetValue("name", "Test UCI Account");
                xrmApp.Entity.SetValue("telephone1", "555-9345");

                xrmApp.Entity.Save();
                xrmApp.ThinkTime(2000);
                Assert.AreEqual<string>("8675309", xrmApp.Entity.GetValue("telephone1"));
            }
        }
```
The UCI test generates this failure output:
```
Test Name:	UCITestCreateAccount
Test FullName:	CrmTestingPoc.UCITest.UCITestCreateAccount
Test Source:	C:\projects\CrmTestingPoc\CrmTestingPoc\UCITest.cs : line 18
Test Outcome:	Failed
Test Duration:	0:01:33.6480588

Result StackTrace:	
at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass12_0.<OpenSubArea>b__0(IWebDriver driver) in C:\dev-work\crm-tools\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 160
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in C:\dev-work\crm-tools\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in C:\dev-work\crm-tools\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 136
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in C:\dev-work\crm-tools\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in C:\dev-work\crm-tools\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.OpenSubArea(String area, String subarea, Int32 thinkTime) in C:\dev-work\crm-tools\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 153
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.Navigation.OpenSubArea(String area, String subarea) in C:\dev-work\crm-tools\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api.UCI\Elements\Navigation.cs:line 23
   at CrmTestingPoc.UCITest.UCITestCreateAccount() in C:\tfs\pubsec\Offender\CrmTestingPoc\CrmTestingPoc\UCITest.cs:line 28
Result Message:	
Test method CrmTestingPoc.UCITest.UCITestCreateAccount threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
```

It looks like these two tests should be equivalent, so I can't figure out why it's breaking.

**Comment by TYLEROL** [comment]
@lucasalexander - It looks like the Unified Interface test is failing between the OpenApp() and OpenSubArea() methods.

It appears that the _Sales_ **app** that you're targeting may not be based on the new Unified Interface. I've included screenshots below from my own org. The **Sales** app is NOT the Unified Interface, compared to the **Sales Hub** which IS the new Unified Interface.

Could you validate based on my screenshots below if you see the same behavior, and if so, whether you observe the same UI differences between **Sales** and the **Sales Hub**? If the UI is the same, try changing the following line in your UCI code:

**BEFORE**
`xrmApp.Navigation.OpenApp("Sales");`

**AFTER**
`xrmApp.Navigation.OpenApp("Sales Hub");`

![image](https://user-images.githubusercontent.com/29415524/46423310-e112d980-c6fb-11e8-9850-87e8d814cb99.png)

![image](https://user-images.githubusercontent.com/29415524/46423333-f12ab900-c6fb-11e8-9935-e5b21e84aad9.png)


Best Regards,
Tyler

**Comment by lucasalexander** [comment]
Thanks! It didn't occur to me to validate that I was actually testing a UCI app. Once I changed to open "Sales Hub," that error went away, but I am now having a problem getting a value from the form to validate a process executed on save.  Here's the relevant code:

`
                xrmApp.ThinkTime(500);
                xrmApp.Navigation.OpenSubArea("Sales", "Accounts");

                xrmApp.ThinkTime(500);
                xrmApp.CommandBar.ClickCommand("New");

                xrmApp.Entity.SetValue("name", "Test UCI Account");
                xrmApp.Entity.SetValue("telephone1", "555-9345");

                xrmApp.Entity.Save();
                xrmApp.ThinkTime(2000);
                var phone1 = xrmApp.Entity.GetValue("telephone1");
                Assert.AreEqual<string>("8675309", phone1);
`

I have a real-time workflow that always sets the value of telephone1 to "8675309," and when I view accounts in a separate browser session I can see the value was set correctly after the Entity.Save. In the browser session that Easy Repro is running, the number doesn't change from the original "555-9345," and the value of the attribute is null when I try to check it using Entity.GetValue. When I manually create an account record in the Sales Hub app, the phone number does update after the save, so I'm not sure why it's not working here.

**Comment by TYLEROL** [comment]
Thanks @lucasalexander for confirming that you were able to get past this step and logged in via the Unified Interface. 

I've moved your latest issue into a new post and should be able to take a look at it tomorrow.

Best Regards,
Tyler

**Comment by ikeselman** [comment]
Hi guys 
If I run same test, 




using (var xrmBrowser = new Api.Browser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
                xrmBrowser.GuidedHelp.CloseGuidedHelp();

                xrmBrowser.ThinkTime(500);
                xrmBrowser.Navigation.OpenSubArea("Sales Hub", "Accounts");

                xrmBrowser.ThinkTime(2000);
                xrmBrowser.Grid.SwitchView("Active Accounts");

                xrmBrowser.ThinkTime(1000);
                xrmBrowser.CommandBar.ClickCommand("New");

                xrmBrowser.ThinkTime(5000);
                xrmBrowser.Entity.SetValue("name", "Test API Account");
                xrmBrowser.Entity.SetValue("telephone1", "555-555-5555");
                //xrmBrowser.Entity.SetValue("websiteurl", "https://easyrepro.crm.dynamics.com");

                xrmBrowser.CommandBar.ClickCommand("Save & Close");
                xrmBrowser.ThinkTime(2000);

Test starts fine and access to Sandbox successful but then while looking for open 'Sales Hub' test fail  
I am getting following error 


Message: 
    Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount threw exception: 
    System.Exception: Login page failed.
  Stack Trace: 
    at <>c.<Login>b__12_2(IWebDriver f)
    at SeleniumExtensions.WaitUntilVisible(IWebDriver driver, By by, TimeSpan timeout, Action`1 successCallback, Action`1 failureCallback)
    at LoginDialog.Login(IWebDriver driver, Uri uri, SecureString username, SecureString password, Action`1 redirectAction)
    at DelegateBrowserCommand`5.ExecuteCommand(IWebDriver driver, Object[] params)
    at BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
    at BrowserCommand`1.Execute[T1,T2,T3,T4](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4)
    at BrowserPage.Execute[TResult,T1,T2,T3,T4](BrowserCommandOptions options, Func`6 delegate, T1 p1, T2 p2, T3 p3, T4 p4)
    at LoginDialog.Login(Uri uri, SecureString username, SecureString password)
    at CreateAccount.WEBTestCreateNewAccount() in CreateAccount.cs line: 25
