### ISSUE TITLE
Lookup search issue ( using v9.0.2 branch)

### ISSUE THREAD

**Issue by SachchinAnnam** [Microsoft/EasyRepro#191]
Hello TYLEROL,
As suggested in the below thread:
https://github.com/Microsoft/EasyRepro/issues/111

I tried the below snippet to search for lookup value 

xrmBrowser.Entity.SelectLookup("parentcustomerid");

xrmBrowser.Lookup.Search("Annam Trading", 15000); //Included a 15 second wait on the Lookup Search

It searches the value from iframe box but it didn't saved the value in the lookup field.
It closes the browser with the below error:

Test Name:	WEBTestCreateNewContact
Test FullName:	Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateContact.WEBTestCreateNewContact
Test Source:	D:\EasyRepro\EasyRepro-beta-v9.0.2\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateContact.cs : line 23
Test Outcome:	Failed
Test Duration:	0:02:21.124237

Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Click()
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.Click(IWebElement element, Boolean ignoreStaleElementException) in D:\EasyRepro\EasyRepro-beta-v9.0.2\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 41
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.<>c__DisplayClass3_0.<ClickWhenAvailable>b__0(IWebDriver d) in D:\EasyRepro\EasyRepro-beta-v9.0.2\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 62
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilClickable(IWebDriver driver, By by, TimeSpan timeout, Action`1 successCallback, Action`1 failureCallback) in D:\EasyRepro\EasyRepro-beta-v9.0.2\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 629
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.ClickWhenAvailable(IWebDriver driver, By by, TimeSpan timeout) in D:\EasyRepro\EasyRepro-beta-v9.0.2\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 59
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.ClickWhenAvailable(IWebDriver driver, By by) in D:\EasyRepro\EasyRepro-beta-v9.0.2\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 52
   at Microsoft.Dynamics365.UIAutomation.Api.XrmPage.<>c__DisplayClass7_0.<SetValue>b__0(IWebDriver driver) in D:\EasyRepro\EasyRepro-beta-v9.0.2\Microsoft.Dynamics365.UIAutomation.Api\XrmPage.cs:line 294
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in D:\EasyRepro\EasyRepro-beta-v9.0.2\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in D:\EasyRepro\EasyRepro-beta-v9.0.2\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 136
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in D:\EasyRepro\EasyRepro-beta-v9.0.2\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in D:\EasyRepro\EasyRepro-beta-v9.0.2\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.XrmPage.SetValue(CompositeControl control) in D:\EasyRepro\EasyRepro-beta-v9.0.2\Microsoft.Dynamics365.UIAutomation.Api\XrmPage.cs:line 287
   at Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateContact.WEBTestCreateNewContact() in D:\EasyRepro\EasyRepro-beta-v9.0.2\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateContact.cs:line 57
Result Message:	
Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateContact.WEBTestCreateNewContact threw exception: 
System.InvalidOperationException: unknown error: Element <iframe frameborder="0" id="contentIFrame1" name="contentIFrame1" title="Content Area" style="border: 0px none; overflow: hidden; position: absolute; left: 0px; right: 0px; height: 100%; width: 100%; visibility: visible;" cd_frame_id_="4289b6230c01ce30eddbef14f687d8d8"></iframe> is not clickable at point (432, 225). Other element would receive the click: <iframe id="InlineDialog_Iframe" name="InlineDialog_Iframe" src="/_controls/lookup/lookupinfo.aspx?AllowFilterOff=0&amp;DefaultType=1&amp;DisableQuickFind=0&amp;DisableViewPicker=0&amp;IsTypeUnresolved=1&amp;LookupStyle=single&amp;ShowNewButton=1&amp;appid=&amp;browse=0&amp;currentObjectType=2&amp;currentid=&amp;dType=1&amp;mrsh=false&amp;objecttypes=1%2c2&amp;suppressfetch=1" style="height: 100%; width: 100%; border: 0px;" cd_frame_id_="b49bdfb918c985714167dd798b638d29"></iframe>
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.16299 x86_64)

Please help us to understand this issue.

**Comment by TYLEROL** [comment]
Thanks @SachinAnnam for raising this issue back up. Two quick questions and I should be able to look at this in a little bit:

1. What screen resolution is your machine configured with?
2. Is the browser window maximized?
3. Version of your Dynamics 365 organization?

I'll test again later today with the Chrome browser and see if my prior results have changed.

**Comment by SachchinAnnam** [comment]
Please find below answers
1. What screen resolution is your machine configured with?
**1920 X 1080**
 2. Is the browser window maximized?
**Yes.**
 3. Version of your Dynamics 365 organization?
**Microsoft Dynamics 365 
 Version 1710 (9.0.2.2081) online**

**Comment by TYLEROL** [comment]
@SachinAnnam - I am encountering a similar problem today, though my test is instead failing when I attempt to click the Save button in the Command Bar after performing the search. This failure is because the Add button does not get clicked correctly from the search dialog window. While I'm not getting the same exception, there is at least some form of issue with interacting with the dialog.

I'm investigating and will update once I have a fix available.

Thanks,
Tyler

**Comment by TYLEROL** [comment]
@SachinAnnam - I spoke with the original creator of these methods and realized I made a mistake in how this set of interactions should be used.

After doing the search, if the expected result is found, then you can call **Lookup.Add()** to click the add button from the lookup dialog.

`                xrmBrowser.Lookup.Add();`

If you need to select a different record other than the first result in the lookup dialog window, you can use Lookup.SelectItem():

```
                xrmBrowser.Lookup.SelectItem(1); 
                xrmBrowser.Lookup.Add();
```

```
        public void WEBTestCreateNewContact()
        {
            using (var xrmBrowser = new Api.Browser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
                xrmBrowser.GuidedHelp.CloseGuidedHelp();

                xrmBrowser.ThinkTime(500);
                xrmBrowser.Navigation.OpenSubArea("Sales", "Contacts");

                xrmBrowser.ThinkTime(1000);
                xrmBrowser.Grid.SwitchView("Active Contacts");

                xrmBrowser.ThinkTime(1000);
                xrmBrowser.CommandBar.ClickCommand("New");

                xrmBrowser.ThinkTime(1000);

                xrmBrowser.Entity.SelectLookup("parentcustomerid");

                xrmBrowser.Lookup.Search("C", 2000); //Included a 2 second wait on the Lookup Search

                //By default, the first record should always be selected. SelectItem() method should only be required if there is more than a single result.
                //xrmBrowser.Lookup.SelectItem(1); 

                xrmBrowser.Lookup.Add();

                xrmBrowser.CommandBar.ClickCommand("Save");
                
            }
        }

```

Please give this a try and let us know if this resolves your scenario.

Best Regards,
Tyler
