### ISSUE TITLE
KeyNotFoundException in XrmBrowser.Grid.Search 

### ISSUE THREAD

**Issue by lilmaster** [Microsoft/EasyRepro#33]
XrmBrowser.Grid.Search types a string in the search text box but it returns the following error.

An exception of type 'System.Collections.Generic.KeyNotFoundException' occurred in Microsoft.Dynamics365.UIAutomation.Browser.dll but was not handled in user code

Additional information: The given key was not present in the dictionary.

**Stack trace**

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Dynamics365.UIAutomation.Api.XrmGridPage.<>c__DisplayClass11_0.<Search>b__0(IWebDriver driver) in C:\Repository\Git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api\Pages\XrmGridPage.cs:line 293
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in C:\Repository\Git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in C:\Repository\Git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 136
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in C:\Repository\Git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in C:\Repository\Git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 180
   at Microsoft.Dynamics365.UIAutomation.Api.XrmGridPage.Search(String searchCriteria, Int32 thinkTime) in C:\Repository\Git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api\Pages\XrmGridPage.cs:line 290
   at Microsoft.Dynamics365.UIAutomation.Sample.CreateAccountTests.TestCreateNewAccount() in C:\Repository\Git\EasyRepro\Microsoft.Dynamics365.UIAutomation.Sample\CreateAccount.cs:line 45

**Comment by dtu11** [comment]
Which version are you working with?

**Comment by dtu11** [comment]
I tested the Search Api with version 8.2 and unable to repro the exception.  Would you mind sharing the test code as well?

**Comment by lilmaster** [comment]
I was testing on v9.0, and I realized the refactoring for v9.0 is being refactored after looking at other posts. Thanks for an update!
