### ISSUE TITLE
Sign out function doesnt seem to work

### ISSUE THREAD

**Issue by troyyer** [Microsoft/EasyRepro#34]
I am getting an error when trying to run the sign out command. Below is the code block i am using

                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password, ADFSLoginAction);
                xrmBrowser.ThinkTime(500);
                xrmBrowser.Navigation.OpenSubArea("Service", "Accounts");
                xrmBrowser.Navigation.SignOut();

OpenQA.Selenium.ElementNotVisibleException occurred
  HResult=0x80131500
  Message=Cannot click on element
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Click()
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.EventFiringWebElement.Click()
   at Microsoft.Dynamics365.UIAutomation.Api.XrmNavigationPage.<>c.<SignOut>b__8_0(IWebDriver driver) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Api\Pages\XrmNavigationPage.cs:line 231
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 192
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.XrmNavigationPage.SignOut(Int32 thinkTime) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Api\Pages\XrmNavigationPage.cs:line 226
   at Microsoft.Dynamics365.UIAutomation.Sample.SigningOut.TestSigningOut() in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Sample\SigningOut.cs:line 28

The Signout function seems to be looking for the element navTabButtonUserInfoSignOutId before it becomes visible on the screen. I think it only becomes visible after the UserInfo link (id navTabButtonUserInfoLinkId) is clicked.

        public BrowserCommandResult<bool> SignOut(int thinkTime = Constants.DefaultThinkTime)
        {
            Browser.ThinkTime(thinkTime);

            return this.Execute(GetOptions($"SignOut"), driver =>
            {
                var userInfo = driver.FindElement(By.XPath(Elements.Xpath[Reference.Navigation.UserInfo]));
                userInfo?.Click();
                var signOut = driver.FindElement(By.XPath(Elements.Xpath[Reference.Navigation.SignOut]));
                signOut?.Click();
                return true;
            });
        }

**Comment by troyyer** [comment]
Forgot to mention that i was using the IE Driver to test this.

**Comment by dtu11** [comment]
Ok this is an issue with the IE driver as the style on the element is set to not visible.   As a workaround you can check out the "OpenSettingsOption" method and there is a fix for this.   

//Bug: 563823 
            //Issue with CRM Style where the Options menu is not visible in IE. Works in Chrome but going to set the style to Display: Block so that we can click it.  
            driver.SetVisible(By.XPath(settingPath), true);
            //End bug fix

I'll work to update the SignOut method to do the same thing.
