### ISSUE TITLE
Error while calling XrmApp.Navigation.OpenSubArea("Sales", Quotes")

### ISSUE THREAD

**Issue by nlipkow** [Microsoft/EasyRepro#347]
I'm in the middle to migrate some UI-Tests to the new UCI. However, I'm getting an error when trying to open a subarea. I'm using v9.1.
The whole steps I'm running are:

```
xrmBrowser.Navigation.OpenApp("Sales Hub");
xrmBrowser.Navigation.OpenSubArea("Sales", "Quotes")
```
The error I'm getting is:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
  Source=Microsoft.Dynamics365.UIAutomation.Api.UCI
  StackTrace:
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass15_0.<OpenAreas>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.OpenAreas(String area, Int32 thinkTime)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass14_0.<OpenSubArea>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.OpenSubArea(String area, String subarea, Int32 thinkTime)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.Navigation.OpenSubArea(String area, String subarea)
   at Encoway.MSCRM.UI.Test.CrmUiTestFeature.WhenINavigateTo(String area, String subarea) in 
```
Thank you in advance for your help!

Screenshot of the UI where the error occurs:
![error](https://user-images.githubusercontent.com/20375505/52261381-839ccc80-2929-11e9-8a52-3b5f0ec7a125.PNG)

**Comment by TYLEROL** [comment]
Hello @nlipkow - This is at the top of our radar for getting a fix out, related to #290 . We were hoping to have something included in the latest releases/v9.1 branch, however the new sitemap had been actively changing causing some issues with navigation stability

I'll discuss with my colleagues about the current status of this and see if we can get something released soon.

Best Regards,
Tyler

**Comment by TYLEROL** [comment]
Related #346

**Comment by ggeiszle** [comment]
Hey @nlipkow,

Please try the latest branch for 9.1.  We added functionality this week to provide support for the new sitemap changes.  If you have any issues with it, please let us know and we'll do the best that we can address them.

Thanks!

**Comment by nlipkow** [comment]
Hello @TYLEROL and @ggeiszle, 
thank you very much for your fast support! 

With the latest changes my issue was solved and so far I haven't encountered any new problems. I will let you know if I run into new difficulties.

Thank you and best regards,
Norman
