### ISSUE TITLE
Grid.Search is not able to click the searchCriteria search icon

### ISSUE THREAD

**Issue by troyyer** [Microsoft/EasyRepro#36]
I am getting the following error when trying to perform a search in a grid. the value is being passed in but the framework is unable to click the search icon. this is the code block I have in OpenAccount.cs

                xrmBrowser.LoginPage.Login(_xrmUri, _username);
                xrmBrowser.Navigation.OpenSubArea("Sales", "Accounts");
                xrmBrowser.Grid.Search("Test");

Test Name:	TestOpenActiveAccount
Test FullName:	Microsoft.Dynamics365.UIAutomation.Sample.OpenAccount.TestOpenActiveAccount
Test Source:	K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Sample\OpenAccount.cs : line 19
Test Outcome:	Failed
Test Duration:	0:01:35.9989661

Result StackTrace:	
at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.<>c.<ClickWhenAvailable>b__2_1(IWebDriver e) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 48
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilClickable(IWebDriver driver, By by, TimeSpan timeout, Action`1 successCallback, Action`1 failureCallback) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 542
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.ClickWhenAvailable(IWebDriver driver, By by, TimeSpan timeout) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 44
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.ClickWhenAvailable(IWebDriver driver, By by) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 37
   at Microsoft.Dynamics365.UIAutomation.Api.XrmGridPage.<>c__DisplayClass11_0.<Search>b__0(IWebDriver driver) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Api\Pages\XrmGridPage.cs:line 293
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 136
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.XrmGridPage.Search(String searchCriteria, Int32 thinkTime) in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Api\Pages\XrmGridPage.cs:line 290
   at Microsoft.Dynamics365.UIAutomation.Sample.OpenAccount.TestOpenActiveAccount() in K:\Master Automation\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Sample\OpenAccount.cs:line 28
Result Message:	
Test method Microsoft.Dynamics365.UIAutomation.Sample.OpenAccount.TestOpenActiveAccount threw exception: 
System.InvalidOperationException: Unable to click element.

I performed the test using both the IE and Chrome Drivers with the same result

**Comment by dtu11** [comment]
Ok, I'll try to repro the scenario with your code.

**Comment by dtu11** [comment]
I noticed that one of your other issues was due to CRM being version 9.0.  Was this exception from a 9.0 org?

**Comment by troyyer** [comment]
@dtu11 Yes it was an exception in 9.0
