### ISSUE TITLE
Not able to find the login elements when using the latest version of Dynamics 365 CE online

### ISSUE THREAD

**Issue by pramodnairm** [Microsoft/EasyRepro#366]
Hi,

When I running the test to create an account I am getting the following error. It is not able to find the login element for email.

OpenQA.Selenium.NoSuchElementException
  HResult=0x80131500
  Message=no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type='email']"}
  (Session info: chrome=72.0.3626.81)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.17134 x86_64)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.<>c__DisplayClass42_0.<WaitUntilAvailable>b__0(IWebDriver d) in C:\D Drive\Samples\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 556
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)

Regards,
Pramod

**Comment by SantoshDutt** [comment]
What is the OnlineCrmUrl you have given in app.config file? Can you re-verify that once and run the test?
Also, sometimes it might take more time to load the Login Page than expected. So increase the DefaultThinkTime in the API. 

Hope that Helps! 

Regards,
Santosh Dutt

**Comment by jlattimer** [comment]
@pramodnairm - did you get this resolved?
