### ISSUE TITLE
Exception with Lookup Functions when more than one record has the same value

### ISSUE THREAD

**Issue by troyyer** [Microsoft/EasyRepro#40]
I noticed that if a lookup result has results with the same value, the function will fail with the error 'An item with the same key has already been added.'  I have a Lookup into the contact list where there are 2 Andrew Smith's and this causes a failure.
I've tried with the following and all failed

```
                xrmBrowser.Entity.SelectLookup("customerid", "Tester"); //attempt 1
                xrmBrowser.Entity.SetValue(new Lookup { Name = "customerid", Value = "Tester" }); //attempt 2
                xrmBrowser.Entity.SelectLookup("customerid", 0); //attempt 3
```

I feel that the lookup functions implementation should allow you to enter in a value and then click the search icon rather than the current implementations where the Lookup field search icon is clicked after finding the lookup element and then checks the lookup results.

I've also tried entering the value into the field and then trying the selectloopup function but with no success

```
                xrmBrowser.Entity.SetValue("customerid", "TEST");
                xrmBrowser.Entity.SelectLookup("customerid", 0);
```

System.ArgumentException occurred
  HResult=0x80070057
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.Dynamics365.UIAutomation.Api.XrmEntityPage.OpenDialog(IWebElement dialog) in C:\AutomationTesting\EasyRepro-master\dynamicscrm\Microsoft.Dynamics365.UIAutomation.Api\Pages\XrmEntityPage.cs:line 358
   at Microsoft.Dynamics365.UIAutomation.Api.XrmEntityPage.<>c__DisplayClass12_0.<SelectLookup>b__0(IWebDriver driver) in C:\AutomationTesting\EasyRepro-master\dynamicscrm\Microsoft.Dynamics365.UIAutomation.Api\Pages\XrmEntityPage.cs:line 290
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in C:\AutomationTesting\EasyRepro-master\dynamicscrm\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in C:\AutomationTesting\EasyRepro-master\dynamicscrm\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 192
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in C:\AutomationTesting\EasyRepro-master\dynamicscrm\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in C:\AutomationTesting\EasyRepro-master\dynamicscrm\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.XrmEntityPage.SelectLookup(String field, String value) in C:\AutomationTesting\EasyRepro-master\dynamicscrm\Microsoft.Dynamics365.UIAutomation.Api\Pages\XrmEntityPage.cs:line 275
   at Microsoft.Dynamics365.UIAutomation.Sample.CreateProgramEnrolmentValidation.TestCreateProgramEnrolmentValidation() in C:\AutomationTesting\EasyRepro-master\dynamicscrm\Microsoft.Dynamics365.UIAutomation.Sample\CreateProgramEnrolmentValidation.cs:line 35

**Comment by dtu11** [comment]
This issue should be fixed in the latest release.  Please download the latest changes and test again. Let us know if you have any issues. 

Thanks
