### ISSUE TITLE
SetValue on Date and Time fields v8.2.3.x OnPrem

### ISSUE THREAD

**Issue by jeesondk** [Microsoft/EasyRepro#401]
### Problem:
When I try to set the value on a Date and Time field on the Appointment entity i get an error.

### Error:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=unknown error: Element <div id="scheduledstart" data-attributename="scheduledstart" data-formid="549a8aa3-c349-4ab9-8bac-4873fa9a7a5c" data-fdeid="PrimaryEntity" data-layout="0" tabindex="1070" class="ms-crm-Inline-Chrome datetime ms-crm-Inline-Chrome nvarchar" aria-describedby="scheduledstart_c">...</div> is not clickable at point (368, 342). Other element would receive the click: <div class="ms-crm-Floating-Div" tabindex="0" style="opacity: 0; z-index: 2004; display: block; height: 899px; width: 1924px;"></div>
  (Session info: chrome=72.0.3626.119)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.16299 x86_64)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Click()
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.EventFiringWebElement.Click()
   at Microsoft.Dynamics365.UIAutomation.Api.XrmPage.<>c__DisplayClass21_0.<SetValue>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.XrmPage.SetValue(DateTimeControl date)
   at Db.Crm.Test.AutomatedRegression.Test.AppointmentTests.CanCreateAppointment() in C:\src\dbcrm-global-testing\src\Db.Crm.Test.AutomatedRegression\Db.Crm.Test.AutomatedRegression.Test\AppointmentTests.cs:line 102
```

### Code:
![setdateandtimefield](https://user-images.githubusercontent.com/39995834/53701754-59430f80-3e00-11e9-919a-e181e8b6edfa.png)

### System:
Version 1612 (8.2.3.8) (DB 8.2.3.8) on-premises
EasyRepro version: "Dynamics365.UIAutomation.Api" version="9.1.0"

Is this a bug or am i just doing it wrong ? :-)

**Comment by Dolph-Dragon** [comment]
Hello @jeesondk ,

This is how i use it : 

            xrmBrowser.Entity.SetValue("sheduledstart", DateTime.Parse("11/11/2018"));
            xrmBrowser.ThinkTime(2000);

I assumed that "sheduledstart" is the name of the field where you want to put the date in.
Maybe this works for you aswell. 

Best regards 
Dolph

**Comment by jeesondk** [comment]
@Dolph-Dragon 
Thanks for the reply, but I disagree :-)

using SetValue(string, DateTime) is depricated
![function_deprecated](https://user-images.githubusercontent.com/39995834/53725971-5599a200-3e6d-11e9-8c2e-26a3d5c6e7f2.png)

Even if I use the depricated method I still get the same error as I described above :-)

**Comment by dtu11** [comment]
I noticed that your CRM version is v8.2 but you are using v9.1 API's.  Have you tried the v8.2 API's and get the same error?   

As an FYI, most of the v9.1 API's will work on older versions.  We try to build them to be resilient to application change but there may be subtle differences between the versions that we either can't address or didn't have time.
