### ISSUE TITLE
QuickCreate SetValue on DateTime field not wokring

### ISSUE THREAD

**Issue by jeesondk** [Microsoft/EasyRepro#402]
### Error:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=unknown error: cannot focus element
  (Session info: chrome=72.0.3626.119)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.16299 x86_64)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text)
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.EventFiringWebElement.SendKeys(String text)
   at Microsoft.Dynamics365.UIAutomation.Api.QuickCreate.<>c__DisplayClass20_0.<SetValue>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.QuickCreate.SetValue(DateTimeControl date)
   at Db.Crm.Test.AutomatedRegression.Test.OpportunityTests.CanCreateOpportunityFromCus360() in C:\src\dbcrm-global-testing\src\Db.Crm.Test.AutomatedRegression\Db.Crm.Test.AutomatedRegression.Test\OpportunityTests.cs:line 119
```

### Code:
![setdatetime_quickcreate](https://user-images.githubusercontent.com/39995834/53702052-5a297080-3e03-11e9-8388-650590f67e78.png)

### Comments:
Works when I use the depricated syntax, xrmBrowser.QuickCreate.SetValue("db_follow_up", DateTime.Now.AddDays(7));

**Comment by dtu11** [comment]
Ok I'll take a look at it.
