### ISSUE TITLE
xrmApp.OnlineLogin.Login throws "Login Page Failed"

### ISSUE THREAD

**Issue by iblejan** [Microsoft/EasyRepro#426]
Steps to reproduce.

1. Create a 30 day Dynamics 365 trial version.

2. In your test:

    client = new WebClient(TestSettings.Options);
    xrmApp = new XrmApp(client);
    xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);

This last line throws "Login page failed". If there's a workaround, can you please point me to that?
Thank you.

**Comment by paulbreuler** [comment]
Had the same issue last Friday and playing around with the code again today to see if I missed something. Stack trace below for reference. 

```
System.Exception
  HResult=0x80131500
  Message=Login page failed.
  Source=Microsoft.Dynamics365.UIAutomation.Api.UCI
  StackTrace:
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c.<Login>b__10_2(IWebDriver f) in C:\Users\[user]\Documents\GitHub\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 112
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilVisible(IWebDriver driver, By by, TimeSpan timeout, Action`1 successCallback, Action`1 failureCallback) in C:\Users\[user]\Documents\GitHub\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 617
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.Login(IWebDriver driver, Uri uri, SecureString username, SecureString password, Action`1 redirectAction) in C:\Users\[user]\Documents\GitHub\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 102
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`5.ExecuteCommand(IWebDriver driver, Object[] params) in C:\Users\[user]\Documents\GitHub\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 134
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in C:\Users\[user]\Documents\GitHub\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 136
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4) in C:\Users\[user]\Documents\GitHub\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 60
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult,T1,T2,T3,T4](BrowserCommandOptions options, Func`6 delegate, T1 p1, T2 p2, T3 p3, T4 p4) in C:\Users\[user]\Documents\GitHub\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 230
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.Login(Uri orgUri, SecureString username, SecureString password) in C:\Users\[user]\Documents\GitHub\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 41
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.OnlineLogin.Login(Uri orgUrl, SecureString username, SecureString password) in C:\Users\[user]\Documents\GitHub\EasyRepro\Microsoft.Dynamics365.UIAutomation.Api.UCI\Elements\OnlineLogin.cs:line 26
   at Microsoft.Dynamics365.UIAutomation.Sample.UCI.AddActivity.UCITestAccountAddAppointment() in C:\Users\[user]\Documents\GitHub\EasyRepro\Microsoft.Dynamics365.UIAutomation.Sample\UCI\Timeline\AddActivity.cs:line 22
```

**Comment by paulbreuler** [comment]
Looks like some of the elements on the app page have changed. I just updated some of the element reference strings and got things working. 

Change Login_CrmMainPage reference in ElementReference.cs:
`{ "Login_CrmMainPage", "//*[@data-id='topBar']"},`

Change Nav_AppMenuButton reference in AppElementReference.cs:
` { "Nav_AppMenuButton" , "//button[@data-id='navbar-switch-app']"},`

Login and OpenApp work for me after this.

**Comment by TYLEROL** [comment]
@iblejan - Thanks for raising this issue. In your scenario with the new trial, after you login to D365 - are you landing inside a UCI app? Or is the system landing you on a generic page which has a list of apps that you can then open?

The latter scenario is a known issue and we're working to accommodate this new behavior so that the loading will be independent of landing page post login.

@paulbreuler - Could you review my comments to iblejan and see if this also applies to you?

Thanks,
Tyler

**Comment by blejan-sabin** [comment]
@TYLEROL - Thank you for investigating. To answer your question, I am taken to the page where all the apps are shown. You know, "Sales", "Customer Service", and so forth.

@paulbreuler -  Your solution works for me as well. Many thanks. Drinks to y'all are on me!

**Comment by paulbreuler** [comment]
@TYLEROL - Thanks for the response. I am landing on the app picker page.

**Comment by mVermaat** [comment]
Thanks for the workaround for the login xpath references. They are needed to fix this. Also if I include the app in the url, I won't land in the app picker page but in the actual app. This is a nice workaround. In my case i go to: https://orgname.crm4.dynamics.com/main.aspx?app=d365default

**Comment by gunjain** [comment]
I am having the same problem with my CRMOL8.2. It was working all fine till yesterday. Now, I am getting this error when I run my tests which are not changed at all. If I put breakpoint and run in debug mode, Login works all fine but it throws error when I run the testcase. Very weird.

**Comment by GowriRamanujapu** [comment]
Log in didn't work as it is, we tweaked it a bit to work for us.
it will be good if Clicking Ok on the Pending email alert is also handled as part of log in.

we changed like below in our local repository and using it as a work around. 
![image](https://user-images.githubusercontent.com/50359658/57675003-5bb2b880-763e-11e9-8bf8-e08b2bafa928.png)
