### ISSUE TITLE
Clicking on a custom button in More Commands gives error, "element not interactable"

### ISSUE THREAD

**Issue by pushpa-kadam** [Microsoft/EasyRepro#436]
If the custom button goes in More Commands, then .click() gives an error, "element not interactable".

If the same button is outside the More Commands, then in that case the button is working as expected.

I suspect the issue is because the Displayed property of the element comes as False. Don't why is this the case. 

**Error Message:**
element not interactable
  (Session info: chrome=73.0.3683.86)
  (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 6.3.9600 x86_64)

**Error Source:**
WebDriver

**Error StackTrace:**
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Click()
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.Click(IWebElement element, Boolean ignoreStaleElementException) in D:\Pushpa Kadam\Trainee\EasyRepro\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 41
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass34_0.<ClickCommand>b__0(IWebDriver driver) in D:\Pushpa Kadam\Trainee\EasyRepro\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 926
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in D:\Pushpa Kadam\Trainee\EasyRepro\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in D:\Pushpa Kadam\Trainee\EasyRepro\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 111

**Comment by rcjohnson113** [comment]
What is the code and screenshot of the UI?

**Comment by pushpa-kadam** [comment]
Contact.cs : 

       //Click Command Share
       xrmApp.CommandBar.ClickCommand("Share");


WebClient.cs : 

internal BrowserCommandResult<bool> ClickCommand(string name, string subname = "", bool moreCommands = false, int thinkTime = Constants.DefaultThinkTime)
        {
            this.Browser.ThinkTime(thinkTime);

            return this.Execute(GetOptions($"Click Command"), driver =>
            {
                IWebElement ribbon = null;

                //Find the button in the CommandBar
                if (driver.HasElement(By.XPath(AppElements.Xpath[AppReference.CommandBar.Container])))
                    ribbon = driver.FindElement(By.XPath(AppElements.Xpath[AppReference.CommandBar.Container]));

                if (ribbon == null)
                {
                    if (driver.HasElement(By.XPath(AppElements.Xpath[AppReference.CommandBar.ContainerGrid])))
                        ribbon = driver.FindElement(By.XPath(AppElements.Xpath[AppReference.CommandBar.ContainerGrid]));
                    else
                        throw new InvalidOperationException("Unable to find the ribbon.");
                }

                //Get the CommandBar buttons
                var items = ribbon.FindElements(By.TagName("li"));

                //Is the button in the ribbon?
                if (items.Any(x => x.GetAttribute("aria-label").Equals(name, StringComparison.OrdinalIgnoreCase)))
                {
                    items.FirstOrDefault(x => x.GetAttribute("aria-label").Equals(name, StringComparison.OrdinalIgnoreCase)).Click(true);
                    driver.WaitForTransaction();
                }
                else
                {
                    //Is the button in More Commands?
                    if (items.Any(x => x.GetAttribute("aria-label").Equals("More Commands", StringComparison.OrdinalIgnoreCase)))
                    {
                        //Click More Commands
                        items.FirstOrDefault(x => x.GetAttribute("aria-label").Equals("More Commands", StringComparison.OrdinalIgnoreCase)).Click(true);
                        driver.WaitForTransaction();

                        //Click the button
                        if (driver.HasElement(By.XPath(AppElements.Xpath[AppReference.CommandBar.Button].Replace("[NAME]", name))))
                        {                            
                            driver.FindElement(By.XPath(AppElements.Xpath[AppReference.CommandBar.Button].Replace("[NAME]", name))).Click(true);
                            driver.WaitForTransaction();
                        }
                        else
                            throw new InvalidOperationException($"No command with the name '{name}' exists inside of Commandbar.");
                    }
                    else
                        throw new InvalidOperationException($"No command with the name '{name}' exists inside of Commandbar.");
                }

                if (!string.IsNullOrEmpty(subname))
                {
                    var submenu = driver.WaitUntilAvailable(By.XPath(AppElements.Xpath[AppReference.CommandBar.MoreCommandsMenu]));

                    var subbutton = submenu.FindElements(By.TagName("button")).FirstOrDefault(x => x.Text == subname);

                    if (subbutton != null)
                    {
                        subbutton.Click(true);
                    }
                    else
                        throw new InvalidOperationException($"No sub command with the name '{subname}' exists inside of Commandbar.");

                }

                driver.WaitForTransaction();

                return true;
            });
        }



![ClickCommand](https://user-images.githubusercontent.com/48991346/55392799-9e6e7480-5559-11e9-857f-2e87afb2d260.png)

**Comment by pushpa-kadam** [comment]
Any updates?
