### ISSUE TITLE
System.InvalidOperationException: The Office 365 sign in page did not return the expected result and the user 'System.Security.SecureString' could not be signed in.

### ISSUE THREAD

**Issue by yoadster** [Microsoft/EasyRepro#469]
Hi, using Dynamics Version 1710 (9.1.0.4044) online with the April 2019 updates enabled. The code sample provided has worked flawlessly pre-update. 

When the login code runs it does actually log the user in and displays the organisation homepage however the following exception occurs and the test fails

Test Name:	Lead_CreateNewLead_SA_MyAccountA2D_Onmicrosoft_Com
Test FullName:	A2D.DynamicsCE.Tests.Features.Sales.Leads.LeadsFeature.Lead_CreateNewLead_SA_MyAccountA2D_Onmicrosoft_Com
Test Source:	C:\Users\Lee.Brennan\Documents\Azure DevOps\A2D.DynamicsCE.Tests\A2D.DynamicsCE.Tests\Features\Sales\Leads\Leads.feature : line 22
Test Outcome:	Failed
Test Duration:	0:00:39.8706294

Result StackTrace:	
at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.<>c__DisplayClass39_0.<WaitUntilAvailable>b__0(IWebDriver d)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilAvailable(IWebDriver driver, By by, TimeSpan timeout, Action`1 successCallback, Action`1 failureCallback)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilAvailable(IWebDriver driver, By by, String exceptionMessage)
   at Microsoft.Dynamics365.UIAutomation.Api.LoginDialog.Login(IWebDriver driver, Uri uri, SecureString username, SecureString password, Action`1 redirectAction)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`5.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult,T1,T2,T3,T4](BrowserCommandOptions options, Func`6 delegate, T1 p1, T2 p2, T3 p3, T4 p4)
   at Microsoft.Dynamics365.UIAutomation.Api.LoginDialog.Login(Uri uri, SecureString username, SecureString password)

The code being used... is as follows:

            var un = username.ToSecureString();
            var pw = password.ToSecureString();

            _configContext.BrowserOptions.Credentials = new BrowserCredentials(un, pw);
            _dynamicsContext.XrmBrowser = new Browser(_configContext.BrowserOptions);
            _dynamicsContext.UserName = username;

            _dynamicsContext.XrmBrowser.LoginPage.Login(_dynamicsContext.EnviromentUrl, un, pw);

**Comment by SachchinAnnam** [comment]
I faced similar issues initially and later i tried to create a local user and logged into the system using the local user. Later executed the scripts with that user and it worked any issues. Please try this approach.

**Comment by jlattimer** [comment]
@yoadster - were you able to resolve this?

**Comment by vaclavrozsypal** [comment]
Hi, I'm facing the same issue..

**Comment by abhisekGupta07** [comment]
i'm still facing the issue.
