### ISSUE TITLE
Test fails when using phantomjs

### ISSUE THREAD

**Issue by devkeydet** [Microsoft/EasyRepro#47]
Everything runs as expected with the chrome driver, but with the phantomjs driver, I get and exception when calling the following:
xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);

Here's the exception:
Test Name:	TestsCrmAsyncRequestResponseSample
Test FullName:	UIAutomationTests.CrmAsyncRequestResponseSampleTests.TestsCrmAsyncRequestResponseSample
Test Source:	C:\github\devkeydet\CrmAsyncRequestResponseSampleV2\UIAutomationTests\CrmAsyncRequestResponseSampleTests.cs : line 27
Test Outcome:	Failed
Test Duration:	0:01:12.2264863

Result StackTrace:	
at Microsoft.Dynamics365.UIAutomation.Api.LoginPage.<>c.<Login>b__12_2(IWebDriver f)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilVisible(IWebDriver driver, By by, TimeSpan timeout, Action`1 successCallback, Action`1 failureCallback)
   at Microsoft.Dynamics365.UIAutomation.Api.LoginPage.Login(IWebDriver driver, Uri uri, SecureString username, SecureString password, Action`1 redirectAction)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`5.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult,T1,T2,T3,T4](String commandName, Func`6 delegate, T1 p1, T2 p2, T3 p3, T4 p4)
   at Microsoft.Dynamics365.UIAutomation.Api.LoginPage.Login(Uri uri, SecureString username, SecureString password)
   at UIAutomationTests.CrmAsyncRequestResponseSampleTests.TestsCrmAsyncRequestResponseSample() in C:\github\devkeydet\CrmAsyncRequestResponseSampleV2\UIAutomationTests\CrmAsyncRequestResponseSampleTests.cs:line 27
Result Message:	
Test method UIAutomationTests.CrmAsyncRequestResponseSampleTests.TestsCrmAsyncRequestResponseSample threw exception: 
System.Exception: Login page failed.

**Comment by dtu11** [comment]
We've just finished up doing some extensive testing for PhantomJs and we've encountered a lot of issues centered around performance with the driver.   The API's are completing but take 10-20x longer to finish which causes issues.     We're evaluating other options for headless support but if you really need a headless option then I would look at running Chrome with the headless option set.   I'll update the board if anything changes for PhantomJs
