### ISSUE TITLE
"Value cannot be null" error when using xrmBrowser.CommandBar.ClickCommand

### ISSUE THREAD

**Issue by JonnySunNZ** [Microsoft/EasyRepro#473]
I got the following error when using xrmBrowser.CommandBar.ClickCommand("New");
`-> error: Value cannot be null.
Parameter name:    ###source`

following are my stepdefinitions:

```private readonly SecureString _username = System.Configuration.ConfigurationManager.AppSettings["AdministratorUsername"].ToSecureString();
        private readonly SecureString _password = System.Configuration.ConfigurationManager.AppSettings["FACDispatcherPassword"].ToSecureString();
        private readonly Uri _xrmUri = new Uri(System.Configuration.ConfigurationManager.AppSettings["OnlineCrmUrl"].ToString());

        [Given(@"I login as ""(.*)""")]
        public void GivenILoginAsAdministrator(string userType)
        {
            xrmBrowser = new Browser(TestSettings.Options);
            xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
        }

        [Given(@"I click ""(.*)"" command")]
        public void GivenIClickCommand(string btn)
        {
            xrmBrowser.ThinkTime(10000);
            xrmBrowser.CommandBar.ClickCommand(btn);

            //Console.WriteLine(btn);
            //try
            //{
            //    xrmBrowser.CommandBar.ClickCommand(btn);
            //    //xrmBrowser.ThinkTime(4000);
            //    //xrmBrowser.Driver.FindElement(By.XPath("//span[contains(text(),'New')]")).Click();
            //}
            //catch (StaleElementReferenceException e)
            //{
            //    Console.WriteLine(e);
            //}
        }
```

Full error message:

```
Test Name:	CreateAWorkOrder
Test FullName:	Downer.FS.UITest.FeatureFiles.WorkOrderFeature.CreateAWorkOrder
Test Source:	C:\Users\jonny.sun\source\repos\MSDynamics\Source\Downer.FS\Downer.FS.UITest\FeatureFiles\WorkOrder.feature : line 5
Test Outcome:	Failed
Test Duration:	0:00:24.4473875

Result StackTrace:	
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dynamics365.UIAutomation.Api.XrmPage.ClickCommandButton(String name, String subName, Boolean moreCommands, Int32 thinkTime) in U:\Desktop\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Api\XrmPage.cs:line 60
   at Microsoft.Dynamics365.UIAutomation.Api.XrmPage.<>c__DisplayClass1_0.<ClickCommand>b__0(IWebDriver driver) in U:\Desktop\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Api\XrmPage.cs:line 42
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in U:\Desktop\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in U:\Desktop\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 136
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in U:\Desktop\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in U:\Desktop\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.XrmPage.ClickCommand(String name, String subName, Boolean moreCommands, Int32 thinkTime) in U:\Desktop\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Api\XrmPage.cs:line 40
   at Downer.FS.UITest.StepDefinition.WorkOrderSteps.GivenIClickCommand(String btn) in C:\Users\jonny.sun\source\repos\MSDynamics\Source\Downer.FS\Downer.FS.UITest\StepDefinition\WorkOrderSteps.cs:line 34
   at lambda_method(Closure , IContextManager , String )
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding, IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(IContextManager contextManager, StepInstance stepInstance)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
   at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
   at Downer.FS.UITest.FeatureFiles.WorkOrderFeature.ScenarioCleanup()
   at Downer.FS.UITest.FeatureFiles.WorkOrderFeature.CreateAWorkOrder() in C:\Users\jonny.sun\source\repos\MSDynamics\Source\Downer.FS\Downer.FS.UITest\FeatureFiles\WorkOrder.feature:line 9
Result Message:	
Test method Downer.FS.UITest.FeatureFiles.WorkOrderFeature.CreateAWorkOrder threw exception: 
System.ArgumentNullException: Value cannot be null.
Parameter name: source
Result StandardOutput:	
-> Using app.config
Given I login as "Administrator"
-> done: WorkOrderSteps.GivenILoginAsAdministrator("Administrator") (6.9s)
And I click "New" command
-> error: Value cannot be null.
Parameter name: source
And I select "Whangarei Water" in "dnz_contractid" lookup field
-> skipped because of previous errors
Then "Whangarei Water" should showed in "msdyn_serviceaccount" field
-> skipped because of previous errors

```

Please help!

**Comment by sammcquistan** [comment]
Could you post a snippit of the code relating to the command bar element you are trying to click on? For example, if you are trying to click "New Contact":
![commandbar](https://user-images.githubusercontent.com/49731029/58565563-96971d80-81f4-11e9-8492-2b061052a11c.PNG)
This would be the code for that element:
![commandbarcode](https://user-images.githubusercontent.com/49731029/58565808-ff7e9580-81f4-11e9-8b20-df12036085c5.PNG)

**Comment by TYLEROL** [comment]
I tested this on my environment running Dynamics 365 v9.1.0.5229 and had no issues. Could you please let us know if this is still an issue, and if so, which version of Dynamics 365 your organization is running?

It sounds as though the initial entry point to get the first list of commands in the CommandBar is returning no results - which we expect to have for the subsequent linq query to see if the desired button is present. If the button isn't present, then we re-check the more commands menu. 

In both scenarios if the GetCommands method returns nothing, this would cause a problem. I'll add a bug fix to enhance this logic for error reporting if it is the source of the issue. 

Warm Regards,
Tyler
