### ISSUE TITLE
WEBTestCreateNewAccount HTTP Request to remote Webdriver timed out

### ISSUE THREAD

**Issue by SARCASMOOO** [Microsoft/EasyRepro#478]
I am using an _on premise Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online_. The browser I am testing with google chrome 74 on windows 2012 R2 in a VM. When I run the WEBTestCreateNewAccount test and it opens the browser but does nothing till I get a browser has time out error. I am using the OnPremise branch of easyRepro. Any ideas? Note the test I am using is not modified and is the same which came packaged with easyRepro.

```
# Test Name:	WEBTestCreateNewAccount
## Test FullName:	
Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount
Test Source:	C:\Users\Administrator\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateAccount.cs : line 21
Test Outcome:	Failed
Test Duration:	0:03:34.5577726

Result StackTrace:	
at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
 --- End of inner exception stack trace ---
    at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Close()
   at Microsoft.Dynamics365.UIAutomation.Browser.InteractiveBrowser.Dispose() in C:\Users\Administrator\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\InteractiveBrowser.cs:line 737
   at Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount() in C:\Users\Administrator\Source\Repos\EasyRepro\Microsoft.Dynamics365.UIAutomation.Sample\Web\Create\CreateAccount.cs:line 44
Result Message:	
Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount threw exception: 
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:50950/session/f7371b797e20c7fe14dd63bd0cce59a6/window timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out


```

**Comment by jlattimer** [comment]
Can you double check the Selenium and Web Driver versions match what is listed as supported?

**Comment by bhomick** [comment]
@jlattimer how can we increase the time out Number for error message " window timed out after 60  seconds  ?? As above describe error message

Thanks in advance

**Comment by jlattimer** [comment]
If it's timing out at 60 seconds and hasn't done anything I think there are other issues. Have you tried downloading & compiling the [On Premise branch](https://github.com/microsoft/EasyRepro/tree/releases/OnPremise)?

**Comment by bhomick** [comment]
@jlattimer  Error is not occuring if environment is working fast but some time environment is low then time out error is occurring.  Can you please help me to Increase Time Out number , so that if environment is slow then also able to run the script.

Thanks in Advance.

**Comment by jlattimer** [comment]
You might look at adding a default timeout to the ChromeDriver initialization in [BrowserDriverFactory.cs](https://github.com/microsoft/EasyRepro/blob/develop/Microsoft.Dynamics365.UIAutomation.Browser/BrowserDriverFactory.cs)

Something like:

```csharp
driver = new ChromeDriver(chromeService, options.ToChrome(), TimeSpan.FromMinutes(5));
```

**Comment by SARCASMOOO** [comment]
@jlattimer I am using the on premise branch and checked that my chrome versions, OS, and chrome driver I used were all compatible. The chrome browser opens up and just sits in the login page of CRM then doesn't do anything.
