### ISSUE TITLE
XrmBrowser.LoginPage.Login does not handle "Stay signed in?" menu

### ISSUE THREAD

**Issue by trentfromrid** [Microsoft/EasyRepro#48]
Sometimes when signing in to crm.dynamics.com, after entering the username and password, the page will ask if you want to stay signed in, offering a yes or no button. I am using the XrmBrowser.LoginPage.Login(Uri url, SecureString username, SecureString password) overload.

Is there a way for me to handle this with what's already included in the project?

**Comment by kaceyarnold** [comment]
I am also running into this problem except it isn't occasional CRM asks everytime I login and the login test fails with "Message: Test method Microsoft.Dynamics365.UIAutomation.Sample.ADFSLogin.TestADFSLogin threw exception: 
OpenQA.Selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.15063 x86_64)
"
Even though the browser window showed that it logged in and is at the would you lie to stay logged in prompt.
If you would tell me which function is checking the page or give me a work around I could at least get the tests rolling.

**Comment by trentfromrid** [comment]
^This. Right now, if I manually interfere and click the "Yes" or "No" button on that page, it will continue for that test fine; however, considering the whole point of automated testing is so that the user doesn't have to interact manually, I would place an update for this scenario to be of high importance.

**Comment by dtu11** [comment]
This issue is fixed in the latest release.  Please test with the latest build and let us know if you run into any issues. 

Thanks

**Comment by trentet** [comment]
Same problem.

System.Exception occurred
  HResult=0x80131500
  Message=Login page failed.
  Source=Microsoft.Dynamics365.UIAutomation.Api
  StackTrace:
   at Microsoft.Dynamics365.UIAutomation.Api.LoginPage.<>c.<Login>b__12_2(IWebDriver f) in C:\Users\Trent\Source\Repos\JT_EasyRepro\Microsoft.Dynamics365.UIAutomation.Api\Pages\LoginPage.cs:line 148
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilVisible(IWebDriver driver, By by, TimeSpan timeout, Action`1 successCallback, Action`1 failureCallback) in C:\Users\Trent\Source\Repos\JT_EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 497
   at Microsoft.Dynamics365.UIAutomation.Api.LoginPage.Login(IWebDriver driver, Uri uri, SecureString username, SecureString password, Action`1 redirectAction) in C:\Users\Trent\Source\Repos\JT_EasyRepro\Microsoft.Dynamics365.UIAutomation.Api\Pages\LoginPage.cs:line 145
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`5.ExecuteCommand(IWebDriver driver, Object[] params) in C:\Users\Trent\Source\Repos\JT_EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 134
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in C:\Users\Trent\Source\Repos\JT_EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 167
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4) in C:\Users\Trent\Source\Repos\JT_EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 60
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult,T1,T2,T3,T4](String commandName, Func`6 delegate, T1 p1, T2 p2, T3 p3, T4 p4) in C:\Users\Trent\Source\Repos\JT_EasyRepro\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 102
   at Microsoft.Dynamics365.UIAutomation.Api.LoginPage.Login(Uri uri, SecureString username, SecureString password) in C:\Users\Trent\Source\Repos\JT_EasyRepro\Microsoft.Dynamics365.UIAutomation.Api\Pages\LoginPage.cs:line 71
   at Microsoft.Dynamics365.UIAutomation.Testing.Tests.JT.BSCR.CreateAccountTests.TestCreateNewAccountDS() in C:\Users\Trent\source\repos\JT_EasyRepro\Microsoft.Dynamics365.UIAutomation.Testing\Tests\JT\BSCR\CreateAccount.cs:line 25
   at Microsoft.Dynamics365.UIAutomation.Testing.Controller.Run() in C:\Users\Trent\source\repos\JT_EasyRepro\Microsoft.Dynamics365.UIAutomation.Testing\Controller.cs:line 18
   at Microsoft.Dynamics365.UIAutomation.Testing.Program.Main(String[] args) in C:\Users\Trent\source\repos\JT_EasyRepro\Microsoft.Dynamics365.UIAutomation.Testing\Program.cs:line 9

**Comment by dtu11** [comment]
This is a different error.   Looks like you are logging in fine but it's timing out when waiting for the CRM Application.   

                    driver.WaitUntilVisible(By.XPath(Elements.Xpath[Reference.Login.CrmMainPage])
                        , new TimeSpan(0, 0, 60),
                        e => { e.WaitForPageToLoad(); },
                        f => { throw new Exception("Login page failed."); });

We've seen the login take longer then 60 seconds to load unfortunately.

**Comment by trentet** [comment]
It's logging in correctly but it does not handle the "Stay Logged In?" menu, which is why the main CRM page does not load.

**Comment by deshazer722** [comment]
I am having this issue with this line of code in the login page. EasyRepro logs me in and I get to my dynamics dashboard. 

![image](https://user-images.githubusercontent.com/73856449/97922723-886efa00-1d22-11eb-8bb5-3f0f354ed4db.png)
I comment it out and wait it works but for some reason I am not sure why this fails.
