### ISSUE TITLE
V9.1 XrmApp.GlobalSearch.FilterWith Method is not functioning as intended

### ISSUE THREAD

**Issue by Bala-Ramadoss** [Microsoft/EasyRepro#505]
GlobalSearch.FilterWith method is not working as intended, it throws an exception even though GlobalSearch(Relevance Search) results have been successfully displayed.

We are unable to drill down the global search results as per the record type (refer to the highlighted part in screenshots attached). 

The stack trace & others details are attached.

**Class:** Microsoft.Dynamics365.UIAutomation.Api.UCI.XrmApp

**Stack Trace:**

System.InvalidOperationException
  HResult=0x80131509
  Message=Filter With picklist is not available
  Source=Microsoft.Dynamics365.UIAutomation.Api.UCI
  StackTrace:
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass119_0.<FilterWith>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.FilterWith(String entity, Int32 thinkTime)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.GlobalSearch.FilterWith(String entity)

Screenshot:

![image](https://user-images.githubusercontent.com/50577926/58249276-097b4100-7d7c-11e9-8982-9dc996b59799.png)

**Comment by Bala-Ramadoss** [comment]
waiting for a resolution on this issue. Please let know

**Comment by Bala-Ramadoss** [comment]
@tyler - Any updates on the fixe for this issue

**Comment by Bala-Ramadoss** [comment]
@tylerol - Any updates on the fix for this issue. Eagerly waiting. Please let know.

**Comment by Bala-Ramadoss** [comment]
@dtu11 @TYLEROL  & team - Request you to Please do the needful

**Comment by dtu11** [comment]
I've added/updated the API's to handle Relevance Search.  I also added a sample test in the GlobalRelevanceSearch.cs file under the Global Search folder.   Please pull the latest changes and test for any issues.   Let me know if you run into any issues, if not then I'll close this issue.

**Comment by TYLEROL** [comment]
Hi @Bala-Ramadoss ,

The fix is in PR #546 . This added the following changes:
 
> ChangeSearchType
> Filter
> GlobalRelevanceSearchTest
> Updated the following API's
> Updated GlobalSearch to handle both search types
> Updated OpenRecord to handle both search types

Please see the new test sample, UCITestGlobalRelevanceSearch, made available last night via the latest changes in releases/v9.1 branch - or via the 9.1.0.5229 NuGet package.

If you have any issues with these changes, please raise new issues as required.

Warm Regards,
Tyler
