### ISSUE TITLE
Sample test, CreaateAccount.cs, failing to login unable to find element by XPATH

### ISSUE THREAD

**Issue by kaceyarnold** [Microsoft/EasyRepro#53]
Using an unmodified CreateAccount.cs pointing app.config at our azure CRM instance, the test fails to find the password field in the redirected login page.  I have looked at XrmElementReference.cs and see that the XPATH is looking for i0118 but when I examine the redirected login page password box it shows *[@id="passwordInput"] as the XPATH attempts to use passwordInput fail with unable to find element passwordInput.  
LoginPage.cs
shows
...
 if (redirectToNewPassword)
                    {
                        driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.Password])).SendKeys(password.ToUnsecureString());
                        driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.Password])).SendKeys(Keys.Tab);
                        driver.FindElement(By.XPath(Elements.Xpath[Reference.Login.Password])).Submit();
                    }
That the code uses XPATH to find the password field.
Any help would be appreciated.

Test Name:	TestCreateNewAccount
Test FullName:	Microsoft.Dynamics365.UIAutomation.Sample.CreateAccountTests.TestCreateNewAccount
Test Source:	C:\Users\kcarn\Documents\Test Studio Projects\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Sample\CreateAccount.cs : line 19
Test Outcome:	Failed
Test Duration:	0:00:09.919094

Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.FindElement(By by)
   at Microsoft.Dynamics365.UIAutomation.Api.LoginPage.Login(IWebDriver driver, Uri uri, SecureString username, SecureString password, Action`1 redirectAction) in C:\Users\kcarn\Documents\Test Studio Projects\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Api\Pages\LoginPage.cs:line 134
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`5.ExecuteCommand(IWebDriver driver, Object[] params) in C:\Users\kcarn\Documents\Test Studio Projects\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 134
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in C:\Users\kcarn\Documents\Test Studio Projects\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 167
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4) in C:\Users\kcarn\Documents\Test Studio Projects\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 60
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult,T1,T2,T3,T4](String commandName, Func`6 delegate, T1 p1, T2 p2, T3 p3, T4 p4) in C:\Users\kcarn\Documents\Test Studio Projects\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 102
   at Microsoft.Dynamics365.UIAutomation.Api.LoginPage.Login(Uri uri, SecureString username, SecureString password) in C:\Users\kcarn\Documents\Test Studio Projects\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Api\Pages\LoginPage.cs:line 71
   at Microsoft.Dynamics365.UIAutomation.Sample.CreateAccountTests.TestCreateNewAccount() in C:\Users\kcarn\Documents\Test Studio Projects\EasyRepro-master\Microsoft.Dynamics365.UIAutomation.Sample\CreateAccount.cs:line 22
Result Message:	
Test method Microsoft.Dynamics365.UIAutomation.Sample.CreateAccountTests.TestCreateNewAccount threw exception: 
OpenQA.Selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"id("i0118")"}
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.15063 x86_64)

+++++++++++++++++++++++++++++++++++++++++++++++
Added 12/2/2017
From XrmElementReferences
                      
            //Login           
            { "Login_UserId", "id(\"i0116\")"},
            { "Login_Password", "id(\"i0118\")"}, 
            { "Login_OldUserId", "id(\"cred_userid_inputtext\")"},

Now when I pull the Xpath selector for the login ID
I get
//*[@id="i0281"]/div[1]/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div[2]/div

Last time I looked i0281 was not i0116
So I do not understand how the selector can even find the Id field.

**Comment by dtu11** [comment]
If it's not the 0365 login page but a redirect to ADFS login then check out the login example on the ADFSLogin.cs.   There will be a redirect action where you can specify the password field details. 

 xrmBrowser.LoginPage.Login(_xrmUri, _username, _password, ADFSLoginAction);

 public void ADFSLoginAction(LoginRedirectEventArgs args)
        {
            //Login Page details go here.  You will need to find out the id of the password field on the form as well as the submit button. 
            //You will also need to add a reference to the Selenium Webdriver to use the base driver. 

            //Example
            //--------------------------------------------------------------------------------------
            //   var d = args.Driver;
            //   d.FindElement(By.Id("passwordInput")).SendKeys(args.Password.ToUnsecureString());
            //   d.ClickWhenAvailable(By.Id("submitButton"), new TimeSpan(0, 0, 2));
            //   d.WaitForPageToLoad();
            //--------------------------------------------------------------------------------------
        }

**Comment by kaceyarnold** [comment]
@dtu11   That works thank you
