### ISSUE TITLE
Batch execution not launching browser after first test runs

### ISSUE THREAD

**Issue by praveenKumarCh** [Microsoft/EasyRepro#577]
When I am triggering the batch execution the first script is working fine and from next script onward _xrmApp.OnlineLogin.Login(url,user name,password) this fun not able to launch the browser itself. It became very difficult to to run as batch execution

**Comment by TYLEROL** [comment]
@praveenKumarCh - Could you provide some more details of how you've configured your tests for batch execution for us to replicate?

**Comment by praveenKumarCh** [comment]
From Test explorer i am trying to execute as a batch but i am getting the issue :Message=Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
![image](https://user-images.githubusercontent.com/50700992/60015596-83ffef00-96a1-11e9-8729-5b0ca3f2203f.png)

**Comment by praveenKumarCh** [comment]
Message=Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it

**Comment by TYLEROL** [comment]
@praveenKumarCh - what browser configuration are you trying to run under? I've done this previously using our OOB sample test groupings, with all but the remote browser option, and have not faced this issue.

**Comment by praveenKumarCh** [comment]
I am using the chrome browser 72.3626.121 version. 

lets consider we have A,B,C test methods 
------------------------------------------------------
### A test method : **launching the browser successfully** and after completing the all the test steps able to **close browser successfully.**
------------------------------------------------------
### B test method : **launching the browser successfully** and after completing the all the test steps not able to **close browser successfully.**
------------------------------------------------------
### C test method : **Browser itself not launching ** , I tried to close browser manually after completing the execution of all steps B test method but same result for C Test method browser not launching 

Stack Error :
System.InvalidOperationException
  HResult=0x80131509
  Message=chrome not reachable
  (Session info: chrome=72.0.3626.121)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.17134 x86_64) (100)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementById(String id)
   at OpenQA.Selenium.By.<>c__DisplayClass16_0.<Id>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.IsVisible(IWebDriver driver, By by)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.Login(IWebDriver driver, Uri uri, SecureString username, SecureString password, Action`1 redirectAction)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`5.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult,T1,T2,T3,T4](BrowserCommandOptions options, Func`6 delegate, T1 p1, T2 p2, T3 p3, T4 p4)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.Login(Uri orgUri, SecureString username, SecureString password, Action`1 redirectAction)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.OnlineLogin.Login(Uri orgUrl, SecureString username, SecureString password, Action`1 redirectAction)
   at PWD_EasyRepro.Tests.Steps.XrmAppSteps.GivenIAmLoggedInToUCI(String p0) in C:\Users\pchowhan\Source\Repos\FTI.EasyRepro.Tests\PWD_EasyRepro.Tests\Steps\XrmAppSteps.cs:line 40
   at PWD_EasyRepro.Tests.Tests.Example.CreateVisit_FromAddActivityButton() in C:\Users\pchowhan\Source\Repos\FTI.EasyRepro.Tests\PWD_EasyRepro.Tests\Tests\Example.cs:line 109

**Comment by TYLEROL** [comment]
Thanks @praveenKumarCh - have you tried updating the ChromeDriver version to match the version of Chrome you are using? 

http://chromedriver.chromium.org/downloads

For version 72, you should upgrade to ChromeDriver 2.45 or 2.46. I can't say with any certainty that this will resolve the issues, but we commonly have faced issues that are resolved by pairing up the appropriate driver to your browser version. It's strange that the the first method is working and then suddenly starts failing on subsequent methods.

Please let me know if the issue persists, or if you see any change in behavior after updating the driver version.

Regards,
Tyler

**Comment by TYLEROL** [comment]
Thanks @praveenKumarCh - have you tried updating the ChromeDriver version to match the version of Chrome you are using? 

http://chromedriver.chromium.org/downloads

For version 72, you should upgrade to ChromeDriver 2.45 or 2.46. I can't say with any certainty that this will resolve the issues, but we commonly have faced issues that are resolved by pairing up the appropriate driver to your browser version. It's strange that the the first method is working and then suddenly starts failing on subsequent methods.

Please let me know if the issue persists, or if you see any change in behavior after updating the driver version.

Regards,
Tyler

**Comment by praveenKumarCh** [comment]
I tried with both chrome driver 2.45 & 2.46 but no luck. Same issue, no changes.

**Comment by TYLEROL** [comment]
@praveenKumarCh - Does this only occur when using the Remote webdriver? Or does it also occur specifying a local browser?

Thanks,
Tyler

**Comment by TYLEROL** [comment]
@praveenKumarCh - Once you're able to validate whether this is related to Remote WebDriver only, or if it reproduces with local browser, please let us know for further assessment.
