### ISSUE TITLE
 xrmBrowser.Navigation.OpenSubArea("Sales", "Opportunities")

### ISSUE THREAD

**Issue by gohiljayraj** [Microsoft/EasyRepro#59]
This works some times and most of the time it gives error

 : **System.NullReferenceException: 'Object reference not set to an instance of an object.'**

**No Inner Exception:** : Null

**Stack Trace**: 

   at Microsoft.Dynamics365.UIAutomation.Api.XrmNavigationPage.<>c__DisplayClass3_0.<OpenSubArea>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.XrmNavigationPage.OpenSubArea(String area, String subArea, Int32 thinkTime)

**Comment by gohiljayraj** [comment]
Another error I am getting while using xrmBrowser.Navigation.OpenSubArea:

System.TypeLoadException occurred
  HResult=0x80131522
  Message=Could not load type 'OpenQA.Selenium.Support.UI.WebDriverWait' from assembly 'WebDriver.Support, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null'.
  Source=Microsoft.Dynamics365.UIAutomation.Browser

**Comment by dtu11** [comment]
It looks like you may be missing the Selenium Support assembly.    Can you check that the Nuget Package is installed and on the correct version?  You may have updated another package and it's looking for 3.8 version of WebDriver.Support

**Comment by gohiljayraj** [comment]
Thanks for your help Daren; this is resolved.
Project I have created has latest Nuget package but "Microsoft.Dynamics365.UIAutomation.Api" and "Microsoft.Dynamics365.UIAutomation.Browser" referring to older versions of Selenium Support so I updated and its started working.
