### ISSUE TITLE
"Not able to navigate SubArea.  If the app is already logged in the specific test instance, (No need to use of_xrmApp.Navigation.OpenApp(p0);) Then _xrmApp.Navigation.OpenSubArea(area, subarea); is not working Issue : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by praveenKumarCh** [Microsoft/EasyRepro#624]
## Question

**What is your question?**

**Comment by praveenKumarCh** [comment]
Result StackTrace:	
at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass15_0.<OpenSubArea>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.OpenSubArea(String area, String subarea, Int32 thinkTime)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.Navigation.OpenSubArea(String area, String subarea)
   at PWD_EasyRepro.Tests.Steps.XrmAppSteps.WhenINavigateToViaAreaSubarea(String entityName, String area, String subarea) in C:\Users\pchowhan\source\repos\FTI.EasyRepro.Tests\PWD_EasyRepro.Tests\Steps\XrmAppSteps.cs:line 97
   at PWD_EasyRepro.Tests.Tests.AccountTest.Account_FieldsVisible() in C:\Users\pchowhan\source\repos\FTI.EasyRepro.Tests\PWD_EasyRepro.Tests\Tests\AccountTest.cs:line 50
Result Message:	
Test method PWD_EasyRepro.Tests.Tests.AccountTest.Account_FieldsVisible threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by praveenKumarCh** [comment]
Result StackTrace:	
at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass15_0.<OpenSubArea>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.OpenSubArea(String area, String subarea, Int32 thinkTime)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.Navigation.OpenSubArea(String area, String subarea)
   at PWD_EasyRepro.Tests.Steps.XrmAppSteps.WhenINavigateToViaAreaSubarea(String entityName, String area, String subarea) in C:\Users\pchowhan\source\repos\FTI.EasyRepro.Tests\PWD_EasyRepro.Tests\Steps\XrmAppSteps.cs:line 97
   at PWD_EasyRepro.Tests.Tests.AccountTest.Account_FieldsVisible() in C:\Users\pchowhan\source\repos\FTI.EasyRepro.Tests\PWD_EasyRepro.Tests\Tests\AccountTest.cs:line 50
Result Message:	
Test method PWD_EasyRepro.Tests.Tests.AccountTest.Account_FieldsVisible threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object. @jlattimer
