### ISSUE TITLE
UCI -  xrmApp.Entity.SetValue(new OptionSet { Name="", Value=""}); throws System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by sagarbajad** [Microsoft/EasyRepro#626]
UCI -  xrmApp.Entity.SetValue(new OptionSet { Name="", Value=""}); throws System.NullReferenceException: Object reference not set to an instance of an object.

Test Name:	TC001ModuleTestCreateNewLead
Test FullName:	Microsoft.Dynamics365.UIAutomation.Sample.UCI.CreateLead.TC001ModuleTestCreateNewLead
Test Source: C:\Users\***\Source\Workspaces\***\UIAutomations\Microsoft.Dynamics365.UIAutomation.Sample\UCI\Create\CreateLead.cs : line 30
Test Outcome:	Failed 
Test Duration:	0:03:24.0647144

Result StackTrace:	
at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass63_0.<SetValue>b__0(IWebDriver driver) in C:\Users\***\Source\Workspaces\***\UIAutomations\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 1723
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in C:\Users\***\Source\Workspaces\***\UIAutomations\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in C:\Users\***\Source\Workspaces\***\UIAutomations\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 136
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in C:\Users***\Source\Workspaces\***\UIAutomations\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in C:\Users\***\Source\Workspaces\***\UIAutomations\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.SetValue(OptionSet option) in C:\Users\***\Source\Workspaces\***\UIAutomations\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 1719
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.Entity.SetValue(OptionSet optionSet) in C:\Users\***\Source\Workspaces\***\UIAutomations\Microsoft.Dynamics365.UIAutomation.Api.UCI\Elements\Entity.cs:line 336
   at Microsoft.Dynamics365.UIAutomation.Sample.Web.Create.MCreateLeadPage.CreateLead(String testName, XrmApp xrmApp, Hashtable ht, String environmentName, Boolean dealerRequired, Boolean Kana, Boolean campRequired) in C:\Users\***\Source\Workspaces\***\UIAutomations\Microsoft.Dynamics365.UIAutomation.Sample\HelperClasses\CreateLeadPage.cs:line 108
   at Microsoft.Dynamics365.UIAutomation.Sample.UCI.CreateLead.TC001ModuleTestCreateNewLead() in C:\Users\***\Source\Workspaces\***\UIAutomations\Microsoft.Dynamics365.UIAutomation.Sample\UCI\Create\CreateLead.cs:line 55
Result Message:	
Test method Microsoft.Dynamics365.UIAutomation.Sample.UCI.CreateLead.TC001ModuleTestCreateNewLead threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by Haywaii** [comment]
Hi sagarbajad,

Is it possible to provide us the code you are doing so the community can try to help? 

In your case you are using OptionSet without filling data for name / value so i don't think it will never work. Name/Value are a key mandatory for xrmApp to find your option set i think.

Thanks,

**Comment by sagarbajad** [comment]
I am not sure what happened but after creating the code in new file, it started working for me.
I purposely did not put any data for name / value just to give the example of the code I am using.

Thanks
