### ISSUE TITLE
[HOW-TO] - Switch Browsers to Test and work through this message

### ISSUE THREAD

**Issue by dagobahsw86** [Microsoft/EasyRepro#651]
## Question

Any Web test or Shared test I choose even to open the browser fails with 

Test Name:	SharedTestOpenEdge
Test FullName:	Microsoft.Dynamics365.UIAutomation.Sample.SharedAPI.OpenWebBrowserTests.SharedTestOpenEdge
Test Source:	C:\Users\Raj\Source\Repos\Project 2\UIEasyRepro-develop\Microsoft.Dynamics365.UIAutomation.Sample\SharedAPI\BrowserTests\BrowserTests.cs : line 40
Test Outcome:	Failed
Test Duration:	0:00:01.3285812

Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserDriverFactory.CreateWebDriver(BrowserOptions options) in C:\Users\Raj\Source\Repos\Project 2\UIEasyRepro-develop\Microsoft.Dynamics365.UIAutomation.Browser\BrowserDriverFactory.cs:line 26
   at Microsoft.Dynamics365.UIAutomation.Browser.InteractiveBrowser.get_Driver() in C:\Users\Raj\Source\Repos\Project 2\UIEasyRepro-develop\Microsoft.Dynamics365.UIAutomation.Browser\InteractiveBrowser.cs:line 85
   at Microsoft.Dynamics365.UIAutomation.Sample.SharedAPI.OpenWebBrowserTests.SharedTestOpenEdge() in C:\Users\Raj\Source\Repos\Project 2\UIEasyRepro-develop\Microsoft.Dynamics365.UIAutomation.Sample\SharedAPI\BrowserTests\BrowserTests.cs:line 44
Result Message:	
Test method Microsoft.Dynamics365.UIAutomation.Sample.SharedAPI.OpenWebBrowserTests.SharedTestOpenEdge threw exception: 
System.InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 74
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.18362 x86_64) (SessionNotCreated)

Any test that I try gets me the same message whether is SharedTestOpenEdge or SharedTestOpenChrome or WEBTestCreateNewAccount

![image](https://user-images.githubusercontent.com/56347499/66476750-46777400-ea8e-11e9-8c1f-e2ba5caa5b69.png)

**Comment by dagobahsw86** [comment]
I am using chrome Version 77.0.3865.90

**Comment by mVermaat** [comment]
Basically your chrome version is too new for the installed version of the chrome driver. Update the chrome driver NuGet package.

**Comment by dagobahsw86** [comment]
Thank you @mVermaat for reviewing my question and coming back to me.

Did that with no luck. Same message.

Also is there a way to switch the tests to firefox or other browsers?

**Comment by duanjuanjuan** [comment]
I also meet this issue, why the Nuget Package can't support the latest version of the chrome? who can update it?

**Comment by duanjuanjuan** [comment]
![image](https://user-images.githubusercontent.com/80037268/109958253-fce19600-7d20-11eb-8f19-314b9033afc4.png)
![Uploading image.png…]()

**Comment by Shakevg** [comment]
> Also is there a way to switch the tests to firefox or other browsers?

@duanjuanjuan Yes, you can set browser via app.config: https://github.com/microsoft/EasyRepro/blob/develop/Microsoft.Dynamics365.UIAutomation.Sample/app.config
https://github.com/microsoft/EasyRepro#supported-browser-webdriver

```
<!-- IE,Chrome,Firefox,Edge,Remote-->
<add key="BrowserType" value="Chrome" />
```

**Comment by Shakevg** [comment]
> I also meet this issue, why the Nuget Package can't support the latest version of chrome? who can update it?

@dagobahsw86 You should have the same major version of Chrome browser and driver.
Instruction [here](https://github.com/microsoft/EasyRepro#browser-driver-download-and-install-instructions)
