### ISSUE TITLE
[BUG] Exception when switching view: An item with the same key has already been added.

### ISSUE THREAD

**Issue by simonbridgwater** [Microsoft/EasyRepro#681]
**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
For the Contact entity only, and only when using Unified Interface, I cannot switch to an alternative view. I get exception 'An item with the same key has already been added.' This occurs regardless of which view I try to switch to within the Contact entity.

**Special formatting / display**  

None

**Code to reproduce**  

```csharp
XrmApp.Grid.SwitchView("Active Contacts");
```
 
**Expected behavior**  

I expect the view to be changed.

**Additional context**  

Exception received (partially redacted for data protection):

System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c.<OpenViewPicker>b__38_0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.OpenViewPicker(Int32 thinkTime)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass39_0.<SwitchView>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.SwitchView(String viewName, Int32 thinkTime)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.Grid.SwitchView(String viewName)
   at [Redacted].AutomatedUiTesting.Utilities.UiActions.UiSwitchView(String viewName) in [Redacted].AutomatedUiTesting\Utilities\UiActions.cs:line 81
   at [Redacted].AutomatedUiTesting.Entities.Contact.Record.UiSwitchViewActive() in [Redacted].AutomatedUiTesting\Entities\Contact\Record.cs:line 252
   at [Redacted].AutomatedUiTesting.Entities.Contact.UiTestFormBasics.DeactivateRecord() in [Redacted].AutomatedUiTesting\Entities\Contact\UiTestFormBasics.cs:line 70

**Comment by AngelRodriguez8008** [comment]
Hi @simonbridgwater,

That is working fine for me. Can you try the latest version?
```
[TestMethod]
public void UCITestOpenContactRelatedEntity_SwitchView()
{
    var client = new WebClient(TestSettings.Options);
    using (var xrmApp = new XrmApp(client))
    {
        xrmApp.OnlineLogin.Login(_xrmUri, _username, _password, _mfaSecrectKey);

        xrmApp.Navigation.OpenApp(UCIAppName.Sales);

        xrmApp.Navigation.OpenSubArea("Service", "Contacts");

        xrmApp.Grid.SwitchView("Active Contacts");

        xrmApp.ThinkTime(2000);
        
        xrmApp.Grid.SwitchView("My Active Contacts");

        xrmApp.ThinkTime(2000);

        xrmApp.Grid.SwitchView("Active Contacts");
        
        xrmApp.ThinkTime(2000);
    }
}
```
