### ISSUE TITLE
[BUG] Get/SetHeaderValue is not working for UCI

### ISSUE THREAD

**Issue by jowells1** [Microsoft/EasyRepro#717]
### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [X] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [X] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [X] Online
  - [ ] On Premise

**Browser**
  - [X] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  

Unable to Get/SetHeaderValue with UCI API.  Debugging error states:
OpenQA.Selenium.NoSuchElementException
  HResult=0x80131500
  Message=no such element: Unable to locate element: {"method":"xpath","selector":"//*[contains(@id, 'leadqualitycode-FieldSectionItemContainer')]"}
  (Session info: chrome=79.0.3945.117)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.<>c__DisplayClass45_0.<WaitUntilAvailable>b__0(IWebDriver d) in C:\Source\Repos\Easy Repro\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 591
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)

**Special formatting / display**  

**Code to reproduce**  

```csharp
xrmApp.OnlineLogin.Login(_xrmUri, _username, _password);

                xrmApp.Navigation.OpenApp(UCIAppName.Sales);

                xrmApp.Navigation.OpenSubArea("Sales", "Leads");

                xrmApp.CommandBar.ClickCommand("New");

                xrmApp.ThinkTime(5000);

                xrmApp.Entity.SetValue("subject", TestSettings.GetRandomString(5, 15));
                xrmApp.Entity.SetValue("firstname", TestSettings.GetRandomString(5, 10));
                xrmApp.Entity.SetValue("lastname", TestSettings.GetRandomString(5, 10));

                OptionSet rating = new OptionSet() { Name = "leadqualitycode", Value = "Cold" };
                xrmApp.Entity.SetHeaderValue(rating);

                xrmApp.Entity.Save();
```
 
**Expected behavior**  

Set the Rating field within the Header on the Lead entity to Cold

**Screenshots**  

![image](https://user-images.githubusercontent.com/34693792/72556989-72607d80-3865-11ea-8d4d-a89ee254d04e.png)

**Additional context**

**Comment by jowells1** [comment]
This issue has been addressed
