### ISSUE TITLE
[HOW-TO] set the path of chromedriver.exe after NuGet Install easyRepro

### ISSUE THREAD

**Issue by xuejunh** [Microsoft/EasyRepro#730]
From the following error message. I have to put chromedriver.exe to the Temp folder. I tried to add chromedriver.exe to the project directory and set the property to always copy but I still get the error. even when I put the chromedriver.exe and set the Path env. I still have the error.

How can I set the path for the easyrepro project to find the chromedriver.exe not in this Temp directory since the chromedriver.exe in the temp directory get deleted automatically from time to time.

Thanks!

Test Name:	UCITestCreateContact
Test FullName:	NunitCRMTestProject.CreateContact.UCITestCreateContact
Test Source:	C:\Users\xhuang\source\repos\NunitCRMTestProject\NunitCRMTestProject\UnitTest1.cs : line 21
Test Outcome:	Failed
Test Duration:	0:00:00.165

Result StackTrace:	
at OpenQA.Selenium.DriverService..ctor(String servicePath, Int32 port, String driverServiceExecutableName, Uri driverServiceDownloadUrl)
   at OpenQA.Selenium.Chrome.ChromeDriverService..ctor(String executablePath, String executableFileName, Int32 port)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserDriverFactory.CreateWebDriver(BrowserOptions options)
   at Microsoft.Dynamics365.UIAutomation.Browser.InteractiveBrowser.get_Driver()
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult,T1,T2,T3,T4](BrowserCommandOptions options, Func`6 delegate, T1 p1, T2 p2, T3 p3, T4 p4)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.Login(Uri orgUri, SecureString username, SecureString password)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.OnlineLogin.Login(Uri orgUrl, SecureString username, SecureString password)
   at NunitCRMTestProject.CreateContact.UCITestCreateContact() in C:\Users\xhuang\source\repos\NunitCRMTestProject\NunitCRMTestProject\UnitTest1.cs:line 26
Result Message:	OpenQA.Selenium.DriverServiceNotFoundException : The file C:\Users\xhuang\AppData\Local\Temp\chromedriver.exe does not exist. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html

**Comment by AngelRodriguez8008** [comment]
See #729

**Comment by xuejunh** [comment]
Thanks for the reply! Could you please list the steps here to modify the app.config to set the path to chromedriver.exe? I could not find relavent details in #729.

**Comment by AngelRodriguez8008** [comment]
Hi @jxyang,

#729 is a Pull Request that is not approved jet. After it become merged, you will be able to set the drivers path in app.config, for ex.:
```xml
<add key="DriversPath" value="YourTestsProject\bin\Debug" />
```

See: the [changed file](https://github.com/microsoft/EasyRepro/pull/729/files#diff-ce019a898b23f81fb001df6c08f9331f)

**Comment by AngelRodriguez8008** [comment]
PR is merged. Now you can do it. Can you please close the Issue?

**Comment by xuejunh** [comment]
NuGet package for easyRepro is still 9.1.0.11711. When the latest will be available ?

**Comment by TYLEROL** [comment]
Hello @xuejunh - We have released Dynamics365.UIAutomation.Api version 9.1.0.12013 a few minutes ago.

Edit: Clarification - the NuGet releases do not include the sample project. Please see PR #729 for changes that you'll need to make to your local project to adopt the DriversPath pattern that @AngelRodrigues8008 introduced for the Sample project.

Warm Regards,
Tyler

**Comment by xuejunh** [comment]
This works for UnitTesting but not for Nunit. @TYLEROL
