### ISSUE TITLE
[BUG] Run test in Nunit failed while succeeded in UnitTest

### ISSUE THREAD

**Issue by xuejunh** [Microsoft/EasyRepro#759]
Our company use Nunit as our test automation framework. I have tried your sample in earlier version using Nunit successfully. But for the sample I cloned today I am failed when modify your code to use Nunit, the error I am getting is:
   UciTestCreateAccount Failed: OpenQA.Selenium.DriverServiceNotFoundException : The file C:\Users\xhuang\AppData\Local\Temp\oqz4aep4.edy\ha5cor2y.adk\chromedriver.exe does not exist. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html
OpenQA.Selenium.DriverServiceNotFoundException : The file C:\Users\xhuang\AppData\Local\Temp\oqz4aep4.edy\ha5cor2y.adk\chromedriver.exe does not exist. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html
   at OpenQA.Selenium.DriverService..ctor(String servicePath, Int32 port, String driverServiceExecutableName, Uri driverServiceDownloadUrl)
   at OpenQA.Selenium.Chrome.ChromeDriverService..ctor(String executablePath, String executableFileName, Int32 port)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserDriverFactory.CreateWebDriver(BrowserOptions options)
   at Microsoft.Dynamics365.UIAutomation.Browser.InteractiveBrowser.get_Driver()
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult,T1,T2,T3,T4](BrowserCommandOptions options, Func`6 delegate, T1 p1, T2 p2, T3 p3, T4 p4)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.Login(Uri orgUri, SecureString username, SecureString password)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.OnlineLogin.Login(Uri orgUrl, SecureString username, SecureString password)
   at NunitCRMTestProject.TestsBase.CreateApp(Boolean privateMode) in C:\Users\xhuang\source\repos\NunitCRMTestProject\NunitCRMTestProject\TestsBase.cs:line 44
   at NunitCRMTestProject.TestsBase.InitTest() in C:\Users\xhuang\source\repos\NunitCRMTestProject\NunitCRMTestProject\TestsBase.cs:line 25
   at NunitCRMTestProject.CreateAccountNunit.InitTest() in C:\Users\xhuang\source\repos\NunitCRMTestProject\NunitCRMTestProject\CreateAccount Nunit.cs:line 12

It looks when using Nunit with your latest sample code, the chromedriver needs to copy to a temp folder which does NOT exist after test run. I reran my Nunit with your earlier sample code, I do not have any issues. Could you fix this asap? Thanks!

**Comment by xuejunh** [comment]
This is related with the private mode. I commented out the line //options.PrivateMode = privateMode || _usePrivateMode; then the test runs for Nunit as well as UnitTesting.

Is private mode a must for the test if we need to switch users in the same testfixture?

**Comment by AngelRodriguez8008** [comment]
The DriverPath & the PrivateMode are not really related, they are configured independently. I think it depends of which Test Runner you use & which NuGet package for the Selenium Web Driver is installed in each Version. You can also put the DriverPath in app.config to indicate where the driver is installed. 

Anyway I also remove this code in the las version of TestsBase (no released yet)

**Comment by AngelRodriguez8008** [comment]
> Is private mode a must for the test if we need to switch users in the same testfixture?

I will say Yes, because in other case you need to SignOut & Close the browser, all instances probably. That will cost more execution time & is unnecessary. [Private Mode](https://en.wikipedia.org/wiki/Private_browsing) do it automatically because the browser do not save any user data, inclusive the user credentials. 

But deactivating PrivateMode, do not means automatically that the credentials will be saved. In Chrome for example is not the case, because "Chrome is being controlled by an automated Software" create automatically a temporal user profile in each test execution, i tried unsuccessfully to set always the same user profile. This behavior can be different in Edge or Firefox.

I was trying not to close the browser after each tests. to save the Login execution time. But as soon I got an alert or modal Dialog in one tests the follow tests fails. It can be done, but I don't wanted to invest more time in this. Also because the MSTest framework was not working properly with the class initialisier methods (in NUnit, that works better). For this reasons is difficult to implement this Logic that works fine for all scenarios.

br

**Comment by AngelRodriguez8008** [comment]
Can you close this also?
