### ISSUE TITLE
[HOW-TO] <Enter Date & Time in UCI>

### ISSUE THREAD

**Issue by sakib5** [Microsoft/EasyRepro#904]
## Question
Getting **OpenQA.Selenium.NoSuchElementException** while entering data in a **date & time** filed
**What is your question?**

Branch: Developer
UCI (XrmApp)
Online
Chrome

I have used multiple types of code to fill up date and time fields, but every time the code will insert the data and throw below error. I seem to find no resources to solve this issue. However earlier it was working fine. But now it is giving error.

Error Type: 
OpenQA.Selenium.NoSuchElementException
  HResult=0x80131500
  Message=no such element: Unable to locate element: {"method":"xpath","selector":"//button[contains(@id,'headerFieldsExpandButton')]"}
  (Session info: chrome=83.0.4103.97)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByXPath(String xpath)
   at OpenQA.Selenium.By.<>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at OpenQA.Selenium.Support.Events.EventFiringWebDriver.FindElement(By by)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.TryCloseHeaderFlyout(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.TrySetValue(IWebDriver driver, ISearchContext container, DateTimeControl control, FormContextType formContext)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass112_0.<SetValue>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.SetValue(DateTimeControl control, FormContextType formContext)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.SetValue(String field, DateTime value, FormContextType formContext, String formatDate, String formatTime)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.Entity.SetValue(String field, DateTime date, String formatDate, String formatTime)
   at TBCRM.UCI.UIAutomation.UnitTest.ClosePhoneCall_RR.ClosePhoneCall() in C:\Users\Prottay\OneDrive - CIBC\Desktop\New folder\D365.UIAutomation\TBCRM.UCI.UIAutomation.UnitTest\ClosePhoneCall_RR.cs:line 48

**Type of code that I used**: 
1.  xrmApp.Entity.SetHeaderValue("Name", DateTime.Parse("6/17/2020")
2.  xrmApp.Entity.SetValue("Name", DateTime.Today);
3.  xrmApp.Entity.SetValue("Name", DateTime.Today.AddMonths(1), "MM/dd/yyyy", "hh:mm tt");
4.  DateTime expectedDate = DateTime.Today.AddDays(1).AddHours(10);
     var start = new DateTimeControl("Name") { Value = expectedDate };
     xrmApp.Entity.SetValue(start);
5.  DateTime? date = DateTime.Today.AddDays(1).AddHours(10);
     var start = new DateTimeControl("Name") { Value = date };
     xrmApp.Entity.SetValue(start);

Screen Shot: 
![image](https://user-images.githubusercontent.com/47485407/85052234-930b6700-b166-11ea-89e9-638c6decfef9.png)

**Comment by badarmunir** [comment]
@sakib5 
               
                DateTime mzk_proposedvisitdatetime = DateTime.Today.AddDays(1).AddHours(10);
                global.xrmApp.Entity.SetValue("mzk_proposedvisitdatetime", mzk_proposedvisitdatetime);

mzk_proposedvisitdatetime is field name try this method this works for me

**Comment by sakib5** [comment]
HI @badarmunir 

Thank you for your response. But can you please explain what is the "global" on your second line of the code?

**Comment by badarmunirr** [comment]
That's nothing remove global and try
