### ISSUE TITLE
[BUG] <Not being able to open a record from global search>

### ISSUE THREAD

**Issue by sakib5** [Microsoft/EasyRepro#913]
## Not being able to open a record from global search window

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [ x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [ x] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [ x] Online
  - [ ] On Premise

**Browser**
  - [ x] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
I am trying to open a record using below code: 

xrmApp.GlobalSearch.Search("Test");
xrmApp.GlobalSearch.FilterWith("Lead");
**xrmApp.GlobalSearch.OpenRecord("Leads", 0);**

But on the last line it is throwing **System.InvalidOperationException** error, full error description is provided below:
System.InvalidOperationException
  HResult=0x80131509
  Message=Entity  was not found in the results
  Source=Microsoft.Dynamics365.UIAutomation.Browser
  StackTrace:
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.<>c__DisplayClass42_0.<WaitUntilAvailable>b__0()
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntil(ISearchContext driver, Func`2 searchFunc, Nullable`1 timeout, Action`1 successCallback, Action failureCallback)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilAvailable(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, Action failureCallback)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilAvailable(ISearchContext driver, By by, Nullable`1 timeout, Action`1 successCallback, String exceptionMessage)
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilAvailable(ISearchContext driver, By by, String exceptionMessage)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass204_0.<OpenGlobalSearchRecord>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.OpenGlobalSearchRecord(String entity, Int32 index, Int32 thinkTime)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.GlobalSearch.OpenRecord(String entity, Int32 index)
   at TBCRM.UCI.UIAutomation.UnitTest.AdvancedFind_ER.DetactClientDuplication_SS.AdvancedFind() in C:\Users\Prottay\OneDrive - CIBC\Desktop\New folder\D365.UIAutomation\TBCRM.UCI.UIAutomation.UnitTest\AdvancedFind_ER.cs:line 39

**Special formatting / display**  

**Code to reproduce**  
xrmApp.GlobalSearch.OpenRecord("Leads", 0)
 
**Expected behavior**  
Something that won't produce the error and will open the record for global search

**Screenshots**  
![image](https://user-images.githubusercontent.com/47485407/86375812-2e670680-bc54-11ea-92c1-f645ce9e1a60.png)

**Additional context**

**Comment by shariquekhan1997** [comment]
@sakib5  Is it solved? How?

**Comment by selvafelix** [comment]
> @sakib5 Is it solved? How?

Try this :
 xrmApp.CommandBar.ClickCommand("YourString");
