### ISSUE TITLE
Problems with Selenium in Azure Devops

### ISSUE THREAD

**Issue by Probstson** [Microsoft/EasyRepro#951]
Hello,

I have a problem with running EasyRepro tests in Azure DevOps which are running locally.

2020-08-24T08:55:55.1300146Z [command]C:\hostedtoolcache\windows\VsTest\16.7.1\x64\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe "@D:\a\_temp\lejgxjfuh4w.tmp"
2020-08-24T08:55:55.5029040Z Microsoft (R) Test Execution Command Line Tool Version 16.7.1
2020-08-24T08:55:55.5029596Z Copyright (c) Microsoft Corporation.  All rights reserved.
2020-08-24T08:55:55.5396835Z vstest.console.exe "D:\a\r1\a\_CRM_Global-BuildSolution\Customizations\UITestAssemblies\Plugins.UITest.dll"
2020-08-24T08:55:55.5397878Z /Settings:"D:\a\_temp\wgzzkfhdvyl.tmp.runsettings"
2020-08-24T08:55:55.5398393Z /Logger:"trx"
2020-08-24T08:55:55.5399018Z /TestAdapterPath:"D:\a\r1\a\_CRM_Global-BuildSolution\Customizations\UITestAssemblies"
2020-08-24T08:55:55.5400188Z /Diag:"D:\a\_temp\Attempt--1_o4vrht.diag"
2020-08-24T08:55:56.9270656Z Starting test execution, please wait...
2020-08-24T08:55:56.9361375Z Logging Vstest Diagnostics in file: D:\a\_temp\Attempt--1_o4vrht.diag
2020-08-24T08:55:57.5548642Z A total of 1 test files matched the specified pattern.
2020-08-24T08:56:05.5729604Z   X TestMethod1 [5s 640ms]
2020-08-24T08:56:05.5730342Z   Error Message:
2020-08-24T08:56:05.5731043Z    Test method Plugins.UITest.CreateContact.TestMethod1 threw exception: 
2020-08-24T08:56:05.5732502Z OpenQA.Selenium.DriverServiceNotFoundException: The file D:\a\r1\a\_CRM_Global-BuildSolution\Customizations\UITestAssemblies\chromedriver.exe does not exist. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html
2020-08-24T08:56:05.5733694Z   Stack Trace:
2020-08-24T08:56:05.5734473Z       at OpenQA.Selenium.DriverService..ctor(String servicePath, Int32 port, String driverServiceExecutableName, Uri driverServiceDownloadUrl)
2020-08-24T08:56:05.5735459Z    at OpenQA.Selenium.Chrome.ChromeDriverService..ctor(String executablePath, String executableFileName, Int32 port)
2020-08-24T08:56:05.5736761Z    at Microsoft.Dynamics365.UIAutomation.Browser.BrowserDriverFactory.CreateWebDriver(BrowserOptions options)
2020-08-24T08:56:05.5737608Z    at Microsoft.Dynamics365.UIAutomation.Browser.InteractiveBrowser.get_Driver()
2020-08-24T08:56:05.5738657Z    at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult,T1,T2,T3,T4,T5](BrowserCommandOptions options, Func`7 delegate, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5)
2020-08-24T08:56:05.5741250Z    at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.Login(Uri orgUri, SecureString username, SecureString password, SecureString mfaSecretKey, Action`1 redirectAction)
2020-08-24T08:56:05.5742965Z    at HDIGlobal.Plugins.UITest.CreateContact.TestMethod1()
2020-08-24T08:56:05.5743567Z   Standard Output Messages:
2020-08-24T08:56:05.5744466Z  Read the Configuration Data
2020-08-24T08:56:05.6744375Z Results File: D:\a\_temp\TestResults\VssAdministrator_WIN-58KOG5EQJ90_2020-08-24_08_56_05.trx
2020-08-24T08:56:05.6810060Z Total tests: 1
2020-08-24T08:56:05.6810780Z      Failed: 1
2020-08-24T08:56:05.6881045Z ##[error]Test Run Failed.

**I tested an easy Google navigation with Selenium which was successfull.**
I've no clue what I'm doing wrong.

**Successfull code:**
ChromeOptions options = new ChromeOptions();
options.AddArgument("headless");
options.AddArgument("no-sandbox");
IWebDriver driver = new ChromeDriver(options);
driver.Navigate().GoToUrl("http://www.google.com");
IWebElement element = driver.FindElement(By.Name("q"));
element.SendKeys("executeautomation");
driver.Close();

**Failed code:**
      var client = new Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient(_options);
      using (var xrmApp = new XrmApp(client))
      {
        xrmApp.ThinkTime(5000);

        var user = GetCredential("CRMUser").ToSecureString();
        var pwd = GetCredential("CRMPassword").ToSecureString();
        var url = new Uri(GetCredential("CRMUrl"));

        Console.WriteLine("Read the Configuration Data");

        xrmApp.OnlineLogin.Login(url, user, pwd);
        client.Browser.Driver.Navigate().GoToUrl(url);

        xrmApp.ThinkTime(5000);

        Console.WriteLine("Application Redirection Successfull");
        try
        {
          xrmApp.Navigation.OpenApp("App");
        }
        catch (Exception)
        {

        }

        Console.WriteLine("Navigation to App successfull");

        xrmApp.ThinkTime(2000);

        client.Browser.Driver.SwitchTo().DefaultContent();
        xrmApp.Navigation.OpenSubArea("Sales", "Contacts");

        Console.WriteLine("Navigation to SubArea successfull");

        xrmApp.ThinkTime(2000);

        xrmApp.CommandBar.ClickCommand("New");

        Console.WriteLine("Clicked on New to create Record");

        xrmApp.ThinkTime(5000);

        Console.WriteLine("Set Value in CRM UCI Form successfull");

        xrmApp.ThinkTime(2000);

        xrmApp.Entity.Save();

        Console.WriteLine("Records has been Saved successfully");
     }

Thanks for your help!

**Comment by Probstson** [comment]
Push

**Comment by Probstson** [comment]
I downgraded Selenium packages to 3.11.2 and now I have the following problem:

2020-09-09T07:58:04.3791802Z Logging Vstest Diagnostics in file: D:\a\_temp\Attempt--1_itcvxm.diag
2020-09-09T07:58:05.0608446Z A total of 1 test files matched the specified pattern.
2020-09-09T07:59:28.1465499Z   X TestMethod1 [1m 19s]
2020-09-09T07:59:28.1484104Z   Error Message:
2020-09-09T07:59:28.1486013Z    Test method Plugins.UITest.CreateContact.TestMethod1 threw exception: 
2020-09-09T07:59:28.1487570Z System.Exception: Login page failed.
2020-09-09T07:59:28.1488070Z   Stack Trace:
2020-09-09T07:59:28.1488672Z       at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c.<Login>b__10_2(IWebDriver f)
2020-09-09T07:59:28.1489752Z    at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.WaitUntilVisible(IWebDriver driver, By by, TimeSpan timeout, Action`1 successCallback, Action`1 failureCallback)
2020-09-09T07:59:28.1491087Z    at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.Login(IWebDriver driver, Uri uri, SecureString username, SecureString password, Action`1 redirectAction)
2020-09-09T07:59:28.1492221Z    at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`5.ExecuteCommand(IWebDriver driver, Object[] params)
2020-09-09T07:59:28.1493416Z    at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
2020-09-09T07:59:28.1494630Z    at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4)
2020-09-09T07:59:28.1495777Z    at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult,T1,T2,T3,T4](BrowserCommandOptions options, Func`6 delegate, T1 p1, T2 p2, T3 p3, T4 p4)
2020-09-09T07:59:28.1496878Z    at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.Login(Uri orgUri, SecureString username, SecureString password)
2020-09-09T07:59:28.1497682Z    at Plugins.UITest.CreateContact.TestMethod1()
2020-09-09T07:59:28.1553811Z   Standard Output Messages:
2020-09-09T07:59:28.1595527Z  Read the Configuration Data
2020-09-09T07:59:28.2553955Z Results File: D:\a\_temp\TestResults\VssAdministrator_WIN-KII2FET158B_2020-09-09_07_59_28.trx
2020-09-09T07:59:28.2678931Z Total tests: 1
2020-09-09T07:59:28.2679720Z      Failed: 1
2020-09-09T07:59:28.2691377Z  Total time: 1.3837 Minutes
